metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: ".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n\
    \    kubernetes cluster.local <DOMAIN_486> <DOMAIN_487> {\n       pods insecure\n\
    \       fallthrough <DOMAIN_486> <DOMAIN_487>\n       ttl 30\n    }\n    prometheus\
    \ :9153\n    forward . /etc/<DOMAIN_488> {\n       max_concurrent 1000\n    }\n\
    \    cache 30\n    loop\n    reload\n    loadbalance\n}\n"
apiVersion: v1
kind: ConfigMap
