metadata:
  name: attachdetach-controller-token-674fd
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: attachdetach-controller
    kubernetes.io/service-account.uid: 41f4a9d4-49e4-4aa2-9e16-4f573438ac0d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
