metadata:
  name: calico-node-token-s8m4r
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: calico-node
    kubernetes.io/service-account.uid: 15485aa1-9f63-4ac8-8cf6-9da744452772
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
