metadata:
  name: pod-garbage-collector-token-jwdft
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: pod-garbage-collector
    kubernetes.io/service-account.uid: 1f5c5988-d49b-4d4a-8b93-192b9ceef78c
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
