metadata:
  name: resourcequota-controller-token-zz4wg
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: resourcequota-controller
    kubernetes.io/service-account.uid: da91e054-f5c6-4dbc-9dff-e9e2c48f7570
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
