metadata:
  name: persistent-volume-binder-token-vx5wr
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: persistent-volume-binder
    kubernetes.io/service-account.uid: 9fd721ae-e7e6-49bd-a59f-e7b95e3f35fc
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
