metadata:
  name: namespace-controller-token-dncb2
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: namespace-controller
    kubernetes.io/service-account.uid: d8a4e761-e373-4ed8-93cc-ac89a320e6a5
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
