metadata:
  name: disruption-controller-token-6z6g5
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: disruption-controller
    kubernetes.io/service-account.uid: bdf2f4f4-b319-4cad-832e-6ca160166722
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
