metadata:
  name: expand-controller-token-99qnp
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: expand-controller
    kubernetes.io/service-account.uid: da6cf30a-576b-4a9b-9b36-dfc3bc2e8f6d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
