metadata:
  name: statefulset-controller-token-sxjbv
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: statefulset-controller
    kubernetes.io/service-account.uid: 8533a20a-4842-4ca4-8120-9dfd23159a4d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
