metadata:
  name: certificate-controller-token-99h99
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: certificate-controller
    kubernetes.io/service-account.uid: 251501d7-7516-45fb-b41c-e8022f4c5836
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
