metadata:
  name: service-controller-token-qw2px
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: service-controller
    kubernetes.io/service-account.uid: 11acf628-cbcf-41a7-92d0-fb0d202bf35e
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
