metadata:
  name: endpointslice-controller-token-gst5k
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: endpointslice-controller
    kubernetes.io/service-account.uid: 856d620a-652b-4e80-a088-992e5f34f8df
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
