metadata:
  name: cronjob-controller-token-9lv25
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: cronjob-controller
    kubernetes.io/service-account.uid: 3bd1216b-8681-4542-999b-d6d7eb6a6bba
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
