metadata:
  name: endpointslicemirroring-controller-token-lfp86
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: endpointslicemirroring-controller
    kubernetes.io/service-account.uid: 75495ef8-21ae-4b4c-ada6-7398c82e237c
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
