metadata:
  name: elasticsearch-data-token-ln7g7
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: elasticsearch-data
    kubernetes.io/service-account.uid: 394c87bf-e441-4e2e-82b5-733ae60db4af
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
