metadata:
  name: calico-kube-controllers-token-d7jqd
  namespace: kube-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: calico-kube-controllers
    kubernetes.io/service-account.uid: 3ea81eed-98cc-46a2-930e-d8b069000bf6
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
