metadata:
  name: elasticsearch-master-token-w88s4
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: elasticsearch-master
    kubernetes.io/service-account.uid: be423a1d-6a51-42fe-a634-14730b47c59d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
