metadata:
  name: elasticsearch-master
  namespace: kube-system
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.5
    component: master
    heritage: Helm
    release: elasticsearch
  annotations: {}
secrets:
- name: elasticsearch-master-token-w88s4
apiVersion: v1
kind: ServiceAccount
