metadata:
  name: apm-server
  namespace: kube-system
  labels:
    app: apm-server
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: elk
  annotations:
    artifact.spinnaker.io/location: <REDACTED:env>
    artifact.spinnaker.io/name: <REDACTED:env>
    artifact.spinnaker.io/type: <REDACTED:env>
    moniker.spinnaker.io/application: <REDACTED:env>
    moniker.spinnaker.io/cluster: <REDACTED:env>
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8200
    targetPort: 8200
  selector:
    app: apm-server
  clusterIP: <IP_78>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
