metadata:
  name: default-token-2n9j6
  namespace: u-qtpdcaqajg
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 1a3176fb-bc8f-4ec2-8a8b-884e6a8dd531
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
