metadata:
  name: registrypullsecret
  namespace: dap
  labels:
    app.kubernetes.io/instance: dap
  annotations: {}
data:
  .dockerconfigjson: <REDACTED:secret>
type: <DOMAIN_138>/dockerconfigjson
apiVersion: v1
kind: Secret
