metadata:
  name: default-token-nh2h5
  namespace: u-ljehyqzo2v
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: bccb7d09-ecef-4db2-8c93-74751a2e8259
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
