metadata:
  name: rook-ceph-mds-ceph-cephfs-a
  namespace: ceph
  labels:
    app: rook-ceph-mds
    ceph-version: 15.2.4-0
    ceph_daemon_id: ceph-cephfs-a
    ceph_daemon_type: mds
    mds: ceph-cephfs-a
    rook-version: v1.4.2
    rook_cluster: ceph
    rook_file_system: ceph-cephfs
  annotations:
    banzaicloud.com/last-applied: '{"metadata":{"labels":{"app":"rook-ceph-mds","ceph-version":"15.2.4-0","ceph_daemon_id":"ceph-cephfs-a","ceph_daemon_type":"mds","mds":"ceph-cephfs-a","rook-version":"v1.4.2","rook_cluster":"ceph","rook_file_system":"ceph-cephfs"},"name":"rook-ceph-mds-ceph-cephfs-a","namespace":"ceph","ownerReferences":[{"apiVersion":"<DOMAIN_668>/v1","blockOwnerDeletion":true,"controller":true,"kind":"CephFilesystem","name":"ceph-cephfs","uid":"cb6d69c2-1722-418a-86e3-22eaac74c928"}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rook-ceph-mds","ceph_daemon_id":"ceph-cephfs-a","mds":"ceph-cephfs-a","rook_cluster":"ceph","rook_file_system":"ceph-cephfs"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"rook-ceph-mds","ceph_daemon_id":"ceph-cephfs-a","ceph_daemon_type":"mds","mds":"ceph-cephfs-a","rook_cluster":"ceph","rook_file_system":"ceph-cephfs"},"name":"rook-ceph-mds-ceph-cephfs-a"},"spec":{"affinity":{},"containers":[{"args":["--fsid=3794cf28-c199-4242-94e1-4e1f35f88262","--keyring=/etc/ceph/keyring-store/keyring","--log-to-stderr=true","--err-to-stderr=true","--mon-cluster-log-to-stderr=true","--log-stderr-prefix=debug
      ","--default-log-to-file=false","--default-mon-cluster-log-to-file=false","--mon-host=$(ROOK_CEPH_MON_HOST)","--mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)","--id=ceph-cephfs-a","--setuser=ceph","--setgroup=ceph","--foreground"],"command":["ceph-mds"],"env":[{"name":"CONTAINER_IMAGE","value":"ceph/ceph:v15.2.4"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_21>"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_20>"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_162>"}}},{"name":"POD_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"<DOMAIN_168>"}}},{"name":"POD_MEMORY_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"<DOMAIN_171>"}}},{"name":"POD_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1","resource":"<DOMAIN_167>"}}},{"name":"POD_CPU_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"<DOMAIN_170>"}}},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"ROOK_CEPH_MON_INITIAL_MEMBERS","valueFrom":{"secretKeyRef":{"key":"mon_initial_members","name":"rook-ceph-config"}}}],"image":"ceph/ceph:v15.2.4","livenessProbe":{"exec":{"command":["env","-i","sh","-c","ceph
      --admin-daemon /run/ceph/<DOMAIN_669> status"]},"initialDelaySeconds":10},"name":"mds","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mds-ceph-cephfs-a-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mds/ceph-ceph-cephfs-a","name":"ceph-daemon-data"}]}],"initContainers":[{"args":["--verbose","--recursive","ceph:ceph","/var/log/ceph","/var/lib/ceph/crash","/var/lib/ceph/mds/ceph-ceph-cephfs-a"],"command":["chown"],"image":"ceph/ceph:v15.2.4","name":"chown-container-data-dir","resources":{},"volumeMounts":[{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/etc/ceph/keyring-store/","name":"rook-ceph-mds-ceph-cephfs-a-keyring","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/var/lib/ceph/mds/ceph-ceph-cephfs-a","name":"ceph-daemon-data"}]}],"restartPolicy":"Always","tolerations":[{"effect":"NoExecute","key":"<DOMAIN_667>/unreachable","operator":"Exists","tolerationSeconds":5}],"volumes":[{"configMap":{"items":[{"key":"config","mode":292,"path":"<DOMAIN_666>"}],"name":"rook-config-override"},"name":"rook-config-override"},{"name":"rook-ceph-mds-ceph-cephfs-a-keyring","secret":{"secretName":"rook-ceph-mds-ceph-cephfs-a-keyring"}},{"hostPath":{"path":"/var/lib/rook/ceph/log"},"name":"rook-ceph-log"},{"hostPath":{"path":"/var/lib/rook/ceph/crash"},"name":"rook-ceph-crash"},{"emptyDir":{},"name":"ceph-daemon-data"}]}}},"status":{}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-mds
      ceph_daemon_id: ceph-cephfs-a
      mds: ceph-cephfs-a
      rook_cluster: ceph
      rook_file_system: ceph-cephfs
  template:
    metadata:
      name: rook-ceph-mds-ceph-cephfs-a
      labels:
        app: rook-ceph-mds
        ceph_daemon_id: ceph-cephfs-a
        ceph_daemon_type: mds
        mds: ceph-cephfs-a
        rook_cluster: ceph
        rook_file_system: ceph-cephfs
    spec:
      volumes:
      - name: rook-config-override
        configMap:
          name: rook-config-override
          items:
          - key: config
            path: <DOMAIN_666>
            mode: 292
          defaultMode: 420
      - name: rook-ceph-mds-ceph-cephfs-a-keyring
        secret:
          secretName: <REDACTED:env>
          defaultMode: 420
      - name: rook-ceph-log
        hostPath:
          path: /var/lib/rook/ceph/log
          type: ''
      - name: rook-ceph-crash
        hostPath:
          path: /var/lib/rook/ceph/crash
          type: ''
      - name: ceph-daemon-data
        emptyDir: {}
      initContainers:
      - name: chown-container-data-dir
        image: ceph/ceph:v15.2.4
        command:
        - chown
        args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /var/lib/ceph/mds/ceph-ceph-cephfs-a
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-mds-ceph-cephfs-a-keyring
          readOnly: true
          mountPath: /etc/ceph/keyring-store/
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: ceph-daemon-data
          mountPath: /var/lib/ceph/mds/ceph-ceph-cephfs-a
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      containers:
      - name: mds
        image: ceph/ceph:v15.2.4
        command:
        - ceph-mds
        args:
        - --fsid=3794cf28-c199-4242-94e1-4e1f35f88262
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=ceph-cephfs-a
        - --setuser=ceph
        - --setgroup=ceph
        - --foreground
        env:
        - name: CONTAINER_IMAGE
          value: ceph/ceph:v15.2.4
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_21>
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_20>
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_162>
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_168>
              divisor: '0'
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_171>
              divisor: '0'
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_167>
              divisor: '1'
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_170>
              divisor: '0'
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_host
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_initial_members
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-mds-ceph-cephfs-a-keyring
          readOnly: true
          mountPath: /etc/ceph/keyring-store/
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: ceph-daemon-data
          mountPath: /var/lib/ceph/mds/ceph-ceph-cephfs-a
        livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/<DOMAIN_669> status
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
      - key: <DOMAIN_667>/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 5
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
