metadata:
  name: rook-ceph-osd-0
  namespace: ceph
  labels:
    app: rook-ceph-osd
    ceph-osd-id: '0'
    ceph-version: 15.2.4-0
    ceph_daemon_id: '0'
    ceph_daemon_type: osd
    failure-domain: <CLEANUP_HOST_4>
    osd: '0'
    portable: 'false'
    rook-version: v1.4.2
    rook_cluster: ceph
  annotations:
    banzaicloud.com/last-applied: '{"metadata":{"labels":{"app":"rook-ceph-osd","ceph-osd-id":"0","ceph-version":"15.2.4-0","ceph_daemon_id":"0","ceph_daemon_type":"osd","failure-domain":"<CLEANUP_HOST_4>","osd":"0","portable":"false","rook-version":"v1.4.2","rook_cluster":"ceph"},"name":"rook-ceph-osd-0","namespace":"ceph","ownerReferences":[{"apiVersion":"<DOMAIN_668>/v1","blockOwnerDeletion":true,"controller":true,"kind":"CephCluster","name":"rook-ceph","uid":"e00e0f95-2d72-4c1e-8b09-fd824f04c347"}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rook-ceph-osd","ceph-osd-id":"0","rook_cluster":"ceph"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"rook-ceph-osd","ceph-osd-id":"0","ceph_daemon_id":"0","ceph_daemon_type":"osd","failure-domain":"<CLEANUP_HOST_4>","osd":"0","portable":"false","rook_cluster":"ceph"},"name":"rook-ceph-osd"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"role","operator":"In","values":["storage-ceph"]}]}]}}},"containers":[{"args":["--foreground","--id","0","--fsid","3794cf28-c199-4242-94e1-4e1f35f88262","--setuser","ceph","--setgroup","ceph","--crush-location=root=default
      host=<CLEANUP_HOST_4>","--log-to-stderr=true","--err-to-stderr=true","--mon-cluster-log-to-stderr=true","--log-stderr-prefix=debug
      ","--default-log-to-file=false","--default-mon-cluster-log-to-file=false","--ms-learn-addr-from-peer=false"],"command":["ceph-osd"],"env":[{"name":"ROOK_NODE_NAME","value":"<CLEANUP_HOST_4>"},{"name":"ROOK_CLUSTER_ID","value":"e00e0f95-2d72-4c1e-8b09-fd824f04c347"},{"name":"ROOK_PRIVATE_IP","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_165>"}}},{"name":"ROOK_PUBLIC_IP","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_165>"}}},{"name":"POD_NAMESPACE","value":"ceph"},{"name":"ROOK_MON_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"data","name":"rook-ceph-mon-endpoints"}}},{"name":"ROOK_MON_SECRET","valueFrom":{"secretKeyRef":{"key":"mon-secret","name":"rook-ceph-mon"}}},{"name":"ROOK_CEPH_USERNAME","valueFrom":{"secretKeyRef":{"key":"ceph-username","name":"rook-ceph-mon"}}},{"name":"ROOK_CEPH_SECRET","valueFrom":{"secretKeyRef":{"key":"ceph-secret","name":"rook-ceph-mon"}}},{"name":"ROOK_CONFIG_DIR","value":"/var/lib/rook"},{"name":"ROOK_CEPH_CONFIG_OVERRIDE","value":"/etc/rook/config/<DOMAIN_677>"},{"name":"ROOK_FSID","valueFrom":{"secretKeyRef":{"key":"fsid","name":"rook-ceph-mon"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_162>"}}},{"name":"ROOK_CRUSHMAP_HOSTNAME","value":"<CLEANUP_HOST_4>"},{"name":"CEPH_VOLUME_DEBUG","value":"1"},{"name":"CEPH_VOLUME_SKIP_RESTORECON","value":"1"},{"name":"DM_DISABLE_UDEV","value":"1"},{"name":"ROOK_OSDS_PER_DEVICE","value":"1"},{"name":"TINI_SUBREAPER"},{"name":"CONTAINER_IMAGE","value":"ceph/ceph:v15.2.4"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_21>"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_20>"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"<DOMAIN_162>"}}},{"name":"POD_MEMORY_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"<DOMAIN_168>"}}},{"name":"POD_MEMORY_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"<DOMAIN_171>"}}},{"name":"POD_CPU_LIMIT","valueFrom":{"resourceFieldRef":{"divisor":"1","resource":"<DOMAIN_167>"}}},{"name":"POD_CPU_REQUEST","valueFrom":{"resourceFieldRef":{"divisor":"0","resource":"<DOMAIN_170>"}}},{"name":"ROOK_OSD_UUID","value":"f9408647-e722-47d6-b5a5-1f303885d7e1"},{"name":"ROOK_OSD_ID","value":"0"},{"name":"ROOK_OSD_STORE_TYPE","value":"bluestore"},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"CEPH_ARGS","value":"-m
      $(ROOK_CEPH_MON_HOST)"}],"image":"ceph/ceph:v15.2.4","livenessProbe":{"exec":{"command":["env","-i","sh","-c","ceph
      --admin-daemon /run/ceph/<DOMAIN_678> status"]},"initialDelaySeconds":45},"name":"osd","resources":{"limits":{"cpu":"3","memory":"20Gi"},"requests":{"cpu":"1","memory":"5Gi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/rook","name":"rook-data"},{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/dev","name":"devices"},{"mountPath":"/run/udev","name":"run-udev"},{"mountPath":"/var/lib/ceph/osd/ceph-0","name":"activate-osd"}]}],"initContainers":[{"command":["/bin/bash","-c","\nset
      -ex\n\nOSD_ID=0\nOSD_UUID=f9408647-e722-47d6-b5a5-1f303885d7e1\nOSD_STORE_FLAG=\"--bluestore\"\nOSD_DATA_DIR=/var/lib/ceph/osd/ceph-\"$OSD_ID\"\nCV_MODE=lvm\nDEVICE=/dev/ceph-16bcdb8b-6cc7-43b2-973b-2513bfcfe8a7/osd-data-f06239da-ac8f-4738-8034-c22f1717ebc0\nMETADATA_DEVICE=\"$ROOK_METADATA_DEVICE\"\nWAL_DEVICE=\"$ROOK_WAL_DEVICE\"\n\n#
      active the osd with ceph-volume\nif [[ \"$CV_MODE\" == \"lvm\" ]]; then\n\tTMP_DIR=$(mktemp
      -d)\n\n\t# activate osd\n\tceph-volume \"$CV_MODE\" activate --no-systemd \"$OSD_STORE_FLAG\"
      \"$OSD_ID\" \"$OSD_UUID\"\n\n\t# copy the tmpfs directory to a temporary directory\n\t#
      this is needed because when the init container exits, the tmpfs goes away and
      its content with it\n\t# this will result in the emptydir to be empty when accessed
      by the main osd container\n\tcp --verbose --no-dereference \"$OSD_DATA_DIR\"/*
      \"$TMP_DIR\"/\n\n\t# unmount the tmpfs since we don''t need it anymore\n\tumount
      \"$OSD_DATA_DIR\"\n\n\t# copy back the content of the tmpfs into the original
      osd directory\n\tcp --verbose --no-dereference \"$TMP_DIR\"/* \"$OSD_DATA_DIR\"\n\n\t#
      retain ownership of files to the ceph user/group\n\tchown --verbose --recursive
      ceph:ceph \"$OSD_DATA_DIR\"\n\n\t# remove the temporary directory\n\trm --recursive
      --force \"$TMP_DIR\"\nelse\n\tARGS=(--device ${DEVICE} --no-systemd --no-tmpfs)\n\tif
      [ -n \"$METADATA_DEVICE\" ]; then\n\t\tARGS+=(--<DOMAIN_679> ${METADATA_DEVICE})\n\tfi\n\tif
      [ -n \"$WAL_DEVICE\" ]; then\n\t\tARGS+=(--<DOMAIN_680> ${WAL_DEVICE})\n\tfi\n\t#
      ceph-volume raw mode only supports bluestore so we don''t need to pass a store
      flag\n\tceph-volume \"$CV_MODE\" activate \"${ARGS[@]}\"\nfi\n\n"],"env":[{"name":"CEPH_VOLUME_DEBUG","value":"1"},{"name":"CEPH_VOLUME_SKIP_RESTORECON","value":"1"},{"name":"DM_DISABLE_UDEV","value":"1"},{"name":"ROOK_CEPH_MON_HOST","valueFrom":{"secretKeyRef":{"key":"mon_host","name":"rook-ceph-config"}}},{"name":"CEPH_ARGS","value":"-m
      $(ROOK_CEPH_MON_HOST)"}],"image":"ceph/ceph:v15.2.4","name":"activate","resources":{"limits":{"cpu":"3","memory":"20Gi"},"requests":{"cpu":"1","memory":"5Gi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/ceph/osd/ceph-0","name":"activate-osd"},{"mountPath":"/dev","name":"devices"},{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true}]},{"args":["--verbose","--recursive","ceph:ceph","/var/log/ceph","/var/lib/ceph/crash"],"command":["chown"],"image":"ceph/ceph:v15.2.4","name":"chown-container-data-dir","resources":{"limits":{"cpu":"3","memory":"20Gi"},"requests":{"cpu":"1","memory":"5Gi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/rook","name":"rook-data"},{"mountPath":"/etc/ceph","name":"rook-config-override","readOnly":true},{"mountPath":"/var/log/ceph","name":"rook-ceph-log"},{"mountPath":"/var/lib/ceph/crash","name":"rook-ceph-crash"},{"mountPath":"/dev","name":"devices"},{"mountPath":"/run/udev","name":"run-udev"},{"mountPath":"/var/lib/ceph/osd/ceph-0","name":"activate-osd"}]}],"nodeSelector":{"<DOMAIN_138>/hostname":"<CLEANUP_HOST_4>"},"restartPolicy":"Always","serviceAccountName":"rook-ceph-osd","volumes":[{"hostPath":{"path":"/var/lib/rook"},"name":"rook-data"},{"configMap":{"items":[{"key":"config","mode":292,"path":"<DOMAIN_666>"}],"name":"rook-config-override"},"name":"rook-config-override"},{"hostPath":{"path":"/var/lib/rook/ceph/log"},"name":"rook-ceph-log"},{"hostPath":{"path":"/var/lib/rook/ceph/crash"},"name":"rook-ceph-crash"},{"hostPath":{"path":"/dev"},"name":"devices"},{"hostPath":{"path":"/run/udev"},"name":"run-udev"},{"emptyDir":{},"name":"activate-osd"}]}}},"status":{}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-osd
      ceph-osd-id: '0'
      rook_cluster: ceph
  template:
    metadata:
      name: rook-ceph-osd
      labels:
        app: rook-ceph-osd
        ceph-osd-id: '0'
        ceph_daemon_id: '0'
        ceph_daemon_type: osd
        failure-domain: <CLEANUP_HOST_4>
        osd: '0'
        portable: 'false'
        rook_cluster: ceph
    spec:
      volumes:
      - name: rook-data
        hostPath:
          path: /var/lib/rook
          type: ''
      - name: rook-config-override
        configMap:
          name: rook-config-override
          items:
          - key: config
            path: <DOMAIN_666>
            mode: 292
          defaultMode: 420
      - name: rook-ceph-log
        hostPath:
          path: /var/lib/rook/ceph/log
          type: ''
      - name: rook-ceph-crash
        hostPath:
          path: /var/lib/rook/ceph/crash
          type: ''
      - name: devices
        hostPath:
          path: /dev
          type: ''
      - name: run-udev
        hostPath:
          path: /run/udev
          type: ''
      - name: activate-osd
        emptyDir: {}
      initContainers:
      - name: activate
        image: ceph/ceph:v15.2.4
        command:
        - /bin/bash
        - -c
        - "\nset -ex\n\nOSD_ID=0\nOSD_UUID=f9408647-e722-47d6-b5a5-1f303885d7e1\n\
          OSD_STORE_FLAG=\"--bluestore\"\nOSD_DATA_DIR=/var/lib/ceph/osd/ceph-\"$OSD_ID\"\
          \nCV_MODE=lvm\nDEVICE=/dev/ceph-16bcdb8b-6cc7-43b2-973b-2513bfcfe8a7/osd-data-f06239da-ac8f-4738-8034-c22f1717ebc0\n\
          METADATA_DEVICE=\"$ROOK_METADATA_DEVICE\"\nWAL_DEVICE=\"$ROOK_WAL_DEVICE\"\
          \n\n# active the osd with ceph-volume\nif [[ \"$CV_MODE\" == \"lvm\" ]];\
          \ then\n\tTMP_DIR=$(mktemp -d)\n\n\t# activate osd\n\tceph-volume \"$CV_MODE\"\
          \ activate --no-systemd \"$OSD_STORE_FLAG\" \"$OSD_ID\" \"$OSD_UUID\"\n\n\
          \t# copy the tmpfs directory to a temporary directory\n\t# this is needed\
          \ because when the init container exits, the tmpfs goes away and its content\
          \ with it\n\t# this will result in the emptydir to be empty when accessed\
          \ by the main osd container\n\tcp --verbose --no-dereference \"$OSD_DATA_DIR\"\
          /* \"$TMP_DIR\"/\n\n\t# unmount the tmpfs since we don't need it anymore\n\
          \tumount \"$OSD_DATA_DIR\"\n\n\t# copy back the content of the tmpfs into\
          \ the original osd directory\n\tcp --verbose --no-dereference \"$TMP_DIR\"\
          /* \"$OSD_DATA_DIR\"\n\n\t# retain ownership of files to the ceph user/group\n\
          \tchown --verbose --recursive ceph:ceph \"$OSD_DATA_DIR\"\n\n\t# remove\
          \ the temporary directory\n\trm --recursive --force \"$TMP_DIR\"\nelse\n\
          \tARGS=(--device ${DEVICE} --no-systemd --no-tmpfs)\n\tif [ -n \"$METADATA_DEVICE\"\
          \ ]; then\n\t\tARGS+=(--<DOMAIN_679> ${METADATA_DEVICE})\n\tfi\n\tif [ -n\
          \ \"$WAL_DEVICE\" ]; then\n\t\tARGS+=(--<DOMAIN_680> ${WAL_DEVICE})\n\t\
          fi\n\t# ceph-volume raw mode only supports bluestore so we don't need to\
          \ pass a store flag\n\tceph-volume \"$CV_MODE\" activate \"${ARGS[@]}\"\n\
          fi\n\n"
        env:
        - name: CEPH_VOLUME_DEBUG
          value: '1'
        - name: CEPH_VOLUME_SKIP_RESTORECON
          value: '1'
        - name: DM_DISABLE_UDEV
          value: '1'
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_host
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST)
        resources:
          limits:
            cpu: '3'
            memory: 20Gi
          requests:
            cpu: '1'
            memory: 5Gi
        volumeMounts:
        - name: activate-osd
          mountPath: /var/lib/ceph/osd/ceph-0
        - name: devices
          mountPath: /dev
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      - name: chown-container-data-dir
        image: ceph/ceph:v15.2.4
        command:
        - chown
        args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        resources:
          limits:
            cpu: '3'
            memory: 20Gi
          requests:
            cpu: '1'
            memory: 5Gi
        volumeMounts:
        - name: rook-data
          mountPath: /var/lib/rook
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: devices
          mountPath: /dev
        - name: run-udev
          mountPath: /run/udev
        - name: activate-osd
          mountPath: /var/lib/ceph/osd/ceph-0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
          readOnlyRootFilesystem: false
      containers:
      - name: osd
        image: ceph/ceph:v15.2.4
        command:
        - ceph-osd
        args:
        - --foreground
        - --id
        - '0'
        - --fsid
        - 3794cf28-c199-4242-94e1-4e1f35f88262
        - --setuser
        - ceph
        - --setgroup
        - ceph
        - --crush-location=root=default host=<CLEANUP_HOST_4>
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --ms-learn-addr-from-peer=false
        env:
        - name: ROOK_NODE_NAME
          value: <CLEANUP_HOST_4>
        - name: ROOK_CLUSTER_ID
          value: e00e0f95-2d72-4c1e-8b09-fd824f04c347
        - name: ROOK_PRIVATE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_165>
        - name: ROOK_PUBLIC_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_165>
        - name: POD_NAMESPACE
          value: ceph
        - name: ROOK_MON_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: rook-ceph-mon-endpoints
              key: data
        - name: ROOK_MON_SECRET
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: mon-secret
        - name: ROOK_CEPH_USERNAME
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: ceph-username
        - name: ROOK_CEPH_SECRET
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: ceph-secret
        - name: ROOK_CONFIG_DIR
          value: /var/lib/rook
        - name: ROOK_CEPH_CONFIG_OVERRIDE
          value: /etc/rook/config/<DOMAIN_677>
        - name: ROOK_FSID
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: fsid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_162>
        - name: ROOK_CRUSHMAP_HOSTNAME
          value: <CLEANUP_HOST_4>
        - name: CEPH_VOLUME_DEBUG
          value: '1'
        - name: CEPH_VOLUME_SKIP_RESTORECON
          value: '1'
        - name: DM_DISABLE_UDEV
          value: '1'
        - name: ROOK_OSDS_PER_DEVICE
          value: '1'
        - name: TINI_SUBREAPER
        - name: CONTAINER_IMAGE
          value: ceph/ceph:v15.2.4
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_21>
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_20>
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_162>
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_168>
              divisor: '0'
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_171>
              divisor: '0'
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_167>
              divisor: '1'
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_170>
              divisor: '0'
        - name: ROOK_OSD_UUID
          value: f9408647-e722-47d6-b5a5-1f303885d7e1
        - name: ROOK_OSD_ID
          value: '0'
        - name: ROOK_OSD_STORE_TYPE
          value: bluestore
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_host
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST)
        resources:
          limits:
            cpu: '3'
            memory: 20Gi
          requests:
            cpu: '1'
            memory: 5Gi
        volumeMounts:
        - name: rook-data
          mountPath: /var/lib/rook
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: devices
          mountPath: /dev
        - name: run-udev
          mountPath: /run/udev
        - name: activate-osd
          mountPath: /var/lib/ceph/osd/ceph-0
        livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/<DOMAIN_678> status
          initialDelaySeconds: 45
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
          readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: <CLEANUP_HOST_4>
      serviceAccountName: rook-ceph-osd
      serviceAccount: rook-ceph-osd
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - storage-ceph
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
