metadata:
  name: rook-ceph-crashcollector-<CLEANUP_HOST_4>
  namespace: ceph
  labels:
    app: rook-ceph-crashcollector
    ceph-version: 15.2.4-0
    ceph_daemon_id: crash
    crashcollector: crash
    kubernetes.io/hostname: <CLEANUP_HOST_4>
    node_name: <CLEANUP_HOST_4>
    rook-version: v1.4.2
    rook_cluster: ceph
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-crashcollector
      kubernetes.io/hostname: <CLEANUP_HOST_4>
      node_name: <CLEANUP_HOST_4>
  template:
    metadata:
      labels:
        app: rook-ceph-crashcollector
        ceph-version: 15.2.4-0
        ceph_daemon_id: crash
        crashcollector: crash
        kubernetes.io/hostname: <CLEANUP_HOST_4>
        node_name: <CLEANUP_HOST_4>
        rook-version: v1.4.2
        rook_cluster: ceph
    spec:
      volumes:
      - name: rook-config-override
        configMap:
          name: rook-config-override
          items:
          - key: config
            path: <DOMAIN_666>
            mode: 292
          defaultMode: 420
      - name: rook-ceph-log
        hostPath:
          path: /var/lib/rook/ceph/log
          type: ''
      - name: rook-ceph-crash
        hostPath:
          path: /var/lib/rook/ceph/crash
          type: ''
      - name: rook-ceph-crash-collector-keyring
        secret:
          secretName: <REDACTED:env>
          defaultMode: 420
      initContainers:
      - name: make-container-crash-dir
        image: ceph/ceph:v15.2.4
        command:
        - mkdir
        - -p
        args:
        - /var/lib/ceph/crash/posted
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      - name: chown-container-data-dir
        image: ceph/ceph:v15.2.4
        command:
        - chown
        args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      containers:
      - name: ceph-crash
        image: ceph/ceph:v15.2.4
        command:
        - ceph-crash
        env:
        - name: CONTAINER_IMAGE
          value: ceph/ceph:v15.2.4
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_21>
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_20>
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_162>
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_168>
              divisor: '0'
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_171>
              divisor: '0'
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_167>
              divisor: '1'
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_170>
              divisor: '0'
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_host
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_initial_members
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST) -k /etc/ceph/crash-collector-keyring-store/keyring
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: rook-ceph-crash-collector-keyring
          readOnly: true
          mountPath: /etc/ceph/crash-collector-keyring-store/
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: <CLEANUP_HOST_4>
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
      - key: <DOMAIN_667>/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: <DOMAIN_667>/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
