metadata:
  name: rook-ceph-osd
  namespace: ceph
  annotations: {}
rules:
- verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  apiGroups:
  - ''
  resources:
  - configmaps
- verbs:
  - get
  - list
  - create
  - update
  - delete
  apiGroups:
  - <DOMAIN_668>
  resources:
  - cephclusters
  - cephclusters/finalizers
apiVersion: <DOMAIN_776>/v1
kind: Role
