metadata:
  name: default-token-j5h9n
  namespace: ceph
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 023a5b55-91fc-49de-a65b-55bb04360580
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
