metadata:
  name: rook-ceph-mon-aj
  namespace: ceph
  labels:
    app: rook-ceph-mon
    ceph_daemon_id: aj
    ceph_daemon_type: mon
    mon: aj
    mon_cluster: ceph
    rook_cluster: ceph
spec:
  ports:
  - name: tcp-msgr1
    protocol: TCP
    port: 6789
    targetPort: 6789
  - name: tcp-msgr2
    protocol: TCP
    port: 3300
    targetPort: 3300
  selector:
    app: rook-ceph-mon
    ceph_daemon_id: aj
    mon: aj
    mon_cluster: ceph
    rook_cluster: ceph
  clusterIP: <IP_5>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
