metadata:
  name: rook-ceph-mgr
  namespace: ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: ceph
spec:
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9283
    targetPort: 9283
  selector:
    app: rook-ceph-mgr
    rook_cluster: ceph
  clusterIP: <IP_54>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
