metadata:
  name: <DOMAIN_62>.v2
  namespace: traefik
  labels:
    modifiedAt: '1783675089'
    name: traefik
    owner: helm
    version: '2'
data:
  release: <REDACTED:secret>
type: <DOMAIN_56>/release.v1
apiVersion: v1
kind: Secret
