metadata:
  name: traefik
  namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-41.0.2
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: web
    nodePort: 30353
  - name: websecure
    protocol: TCP
    port: 443
    targetPort: websecure
    nodePort: 32109
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  clusterIP: <IP_36>
  clusterIPs:
  - <IP_36>
  type: LoadBalancer
  sessionAffinity: <REDACTED:env>
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
apiVersion: v1
kind: Service
