metadata:
  name: crt-local-local-fleet-local-owner-2rrvd6ognb
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: e5268cbc134cf1753a3eccabfce3ae9690245fef
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SRO2/bMBDHv0pxs6jWkp8EurRDh26GOxUdjtRJZs2HQJ4UJIa+eyDJDjzEgbNJ4N39H78zOGKskBHkGdD7wMgm+DT+BvWfNCfiPJqQa2S2lJvw1VQgATs+ijaGXvSF0JGViMGSMr4yvoHs7nJ48hRF059AgkOPDTnyfDPQl9mX38ZX33/aLjHFfbB0INdaZPrx4HmPjkCCDRqtqC0Ri/l7en5oPbWo327AkIGONFVzMI4So2tB+s7aDCwqsh8WdsR0BAm0KtZbrfSiXOp6sVmVWJLWqGpNJdJuvftWLFc11aPaJYGOV+d3sogixr5ah8YrmLeuxm9Gx4MjnT3VE+bW/Iqha0FCVKjzEWWI5mWKl5+2KTcBMjgZP4Ie+4d3DOkZz6XSIYPUzfFB/v2sxp80UblodMKFzaZ8ZuYlDP+G1wAAAP//Kl9Z46UCAAA
    objectset.rio.cattle.io/id: auth-prov-v2-crtb-rolebinding
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=ClusterRoleTemplateBinding
    objectset.rio.cattle.io/owner-name: local-fleet-local-owner
    objectset.rio.cattle.io/owner-namespace: local
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-mo773yttt4
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: crt-local-cluster-owner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
