metadata:
  name: crt-local-u-b4qkhsnliz-admin-oxyidght3v
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: c91799d7d33c6d54875d60e0de3aa002f5734fc1
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SRS4/TMBDHvwqacxyym3aztcQFDhy4VeWEOEzsSWLiR7AnAVr1uyOnRVTioe7Rkv/zf/xO4IhRIyPIE6D3gZFN8Ck/Q/uFFCfiMppQKmS2VJrw2miQgDMPYophEcujUJFbEYOl1nhtfA/FP8Xhm6co+mUECQ499uTI882HpS5efTBev3ln58QU98HSgdxkkentnec9OgIJs2g3X8cheWuOArUz/i5lmlBluQ0KLZwLUJHWVQ7GUWJ0E0g/W1uAxZbsf7caMA0gQe0emt1ON7qu1ZPebp6brX6qqNJUI1bVY7dt6k2nHrLbNbyKLNYE4s8aInz/YXQ/cL3ARfArc2eJrrp8KzPZU7fCncz7GOYJJMQWVZkBhmiOa7NyfE6lCVDAaHzGm1eHv2RRFyhiXSs7pPnSHOSnl3p8TBR/e9y2hPPn888AAAD//6Odu1ybAgAA
    objectset.rio.cattle.io/id: auth-prov-v2-crtb-rolebinding
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=ClusterRoleTemplateBinding
    objectset.rio.cattle.io/owner-name: u-b4qkhsnliz-admin
    objectset.rio.cattle.io/owner-namespace: local
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-b4qkhsnliz
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: crt-local-cluster-owner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
