metadata:
  name: r-cluster-local-view
  namespace: fleet-local
rules:
- verbs:
  - get
  apiGroups:
  - <DOMAIN_551>
  resources:
  - clusters
  resourceNames:
  - local
apiVersion: <DOMAIN_776>/v1
kind: Role
