metadata:
  name: request-mnk27
  namespace: fleet-local
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 283c5a882dad3abad13b6e5ac6f9f4d5eafdff1e
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSy67TMBCGXwXN2ukhTdJLJFYgsUAC6QixQV2M7XFr4tjBHpdFlXdHzuFyVBEES8/vuXz/zA1GYtTICP0N0PvAyDb4VJ5BfiHFiXgTbdgoZHa0seHBauhBuZyYYhXpbBPHJQvEak745ilW5+sAPRhHxM+0a41uumAtXryzXr96/VT58X8KexwJeoj0NVPiavTDdv9PSWlCRT9nqlxQ6GAWoCItjT/akRLjOEHvs3MCHEpyizv3FCN6PFOxhmOmvzS/YLpAD9tDozo8HLYadYMSdd3IHXWoduZoWt0RGm1MTWWcFbw1AAEL4CMZiuQVJeg/3wAn+4liKnau7wAESBfU8KEUeEOOFvt7gy6RABU8x+AcxV+hwfrC/OelrcydlwtqXrbHvd5hddwbWbUo20o2u64yddPWjdSm3nYwn2YBMbvfDG9jyFN53TPASUCkFHJU9L44U/48GfJMWaI/jjc9JEbOqehXinLRJmR1gdN8mr8HAAD//3sg1ygdAwAA
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-mnk27
    objectset.rio.cattle.io/owner-namespace: fleet-local
rules:
- verbs:
  - patch
  apiGroups:
  - <DOMAIN_474>
  resources:
  - clusters/status
  resourceNames:
  - local
apiVersion: <DOMAIN_776>/v1
kind: Role
