metadata:
  name: r-cluster-local-view-p-67wv8-u-muss3v2lek-member-sbrueawyjs
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: e2e21320c12e00b2947217cb7de25e3490e7a878
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSS4/TQBCE/wrqs8c4Ywc/JC5w4MAFRQsXxKFn3E5mMw9rHo4gyn9HE28gB1jt3mxpurrq6zqDoYgjRoThDGitixiVsyH/OvFIMgaKpVeulBijplK5t2qEATDFA5u9W9jC2eyjYN5pEsqOyu6h+O+wO1nybL8cYQCDFvdkyMa7B0tdvPms7Pj+i3dZYuc0PZCZNUb68EJ5i4ZggMRMCqFeuKYjM2QE+ReNhhllnp/Zu/a0dHApQHq6gnlQhkJEM8Ngk9YFaBSkn8V1wHCAAYgT39S8khtOVSV437R800rRjsS3VDd9RS127XXbk3/PpE4hkmfaSdRsUXRiT6bYP8KxIHwiPP18DLCK3JJMmiiuKplATrqjiTxZSQGG72fAWX0jH5SzObh3i8rfyu7vT7OBAo7K5vt/XJ3BH7M38bTWY9uMdYvEOpyINV2FrOfVlo1Tv+W8b3BsBVx+XArItdnRdO3frD55l+YcXaAsc8ecV7+u5MtjF0rl/jrIxYBnWWWUIa1nuYV8xYKv4T7fPe/s/HcAAAD//zN0Kfo7AwAA
    objectset.rio.cattle.io/id: auth-prov-v2-prtb-rolebinding
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=ProjectRoleTemplateBinding
    objectset.rio.cattle.io/owner-name: u-muss3v2lek-member
    objectset.rio.cattle.io/owner-namespace: p-67wv8
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-muss3v2lek
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: r-cluster-local-view
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
