metadata:
  name: r-cluster-local-view-p-mwkwc-creator-project-owner-ajejumyl6e
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: d82dbc367eb58c34cc90cc8130bf504ff7cb09aa
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSsY7bPBCEX+XH1qJ+nS2fJQFpkiJFmsC4pAlSLMmVTZviEiQlIWf43QNa58RFcrh0Ergczjc7ZxgoocaE0J0BneOEybCL+ZflkVSKlMpguFSYkqXS8P9GQwc4poPwgScxrYQPSYrAlqRx2rg9FH+9zLOjIPbTCToY0OGeBnLpbmBaF/99Mk6/+xw4S+zY0hMN3mKi92+UdzgQdKACYeKQbeZpcT180+XoUWUFL4b5NCu4FIuYYfdkBooJBw+dG60twKIk+2pgB4wH6EA3Ky3V+nFLctOoda1UWynVPKwr2W+quu+3SlYtYn7thSAIZceYKAjLCq2YDM3ixZT4I57AIx3H4Yd9JFhkbiy9JUqLTs4gD++op0BOUYTu2xnQm68UomGX0QNPJn8bt79fzwMUcDIud+DD4g1+2b2Jj0tFNrVeb5FEgz2JuqlQtKtqI3Tfblartka9lXD5fikgV2dH/bWD3nwMPPoML1GVuWcczPM1+/LUxNLwbwe5HPBqWjnMOC6LuUH+wwNf4j3fKNiPz/Xcs8bs/GcAAAD//+WMN+I/AwAA
    objectset.rio.cattle.io/id: auth-prov-v2-prtb-rolebinding
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=ProjectRoleTemplateBinding
    objectset.rio.cattle.io/owner-name: creator-project-owner
    objectset.rio.cattle.io/owner-namespace: p-mwkwc
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-opuz4wfoda
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: r-cluster-local-view
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
