metadata:
  name: r-cluster-local-view-p-wnc8s-creator-project-owner-dw2ccrzuk7
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: 81f27948d2a3f72875d23cb2d602f2e4aef085e5
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SST4/TMBDFvwqacxy6bkL+SFzgwIELqhYuiMPEnrSmjseynVTaqt8dudlCD7Babok8fn6/N+8MEyXUmBD6M6BznDAZdjH/8vCTVIqUymC4VJiSpdLwW6OhB5zTQfjAi1ik8CENIrClwTht3B6Kf17mk6Mg9ssRepjQ4Z4mculuYNkWbz4bp99/CZwldmzpkSZvMdGHV8o7nAh6UIEwccg287S4Hr7qcvSosoIXJ6faCJdiFTPsHs1EMeHkoXeztQVYHMi+GNgB4wF6aB9G2XRVqyVux0a2Ta3lVg1Sv9vIUVKFNG7amur82jNBEMrOMVEQlhVasRg6iWdT4q94Qp+kUuFpPjawytxYRkuUVp2cQR7e0UiBnKII/fczoDffKETDLqMHXkz+Nm5/v54HKOBoXO7Ax9Ub/LZ7E5/XitSV3jZIosWRRNVuUHRyUws9drWUXYW6GeDy41JArs6OxmsHvfkUePYZfkBV5p5xME/X7MtjG0vDfxzkcsCLaeUw47wu5gb5Hw98jfd8c6QgukOnfPb9KwAA//9kpriAPQMAAA
    objectset.rio.cattle.io/id: auth-prov-v2-prtb-rolebinding
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=ProjectRoleTemplateBinding
    objectset.rio.cattle.io/owner-name: creator-project-owner
    objectset.rio.cattle.io/owner-namespace: p-wnc8s
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: user-9h9cp
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: r-cluster-local-view
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
