metadata:
  name: crt-local-cluster-admin
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: 681219f11986442341da5c4fc12c7e769fe6d0c3
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yRTY/TMBCG/wqaI4pLk6ZtYokTBw5IHFYrLiiHiT1pzfojsifhUOW/Ize7bIS0wM2ez2fe9waOGDUygrwBeh8Y2QSf8jf0P0hxIt5FE3YKmS3tTPhgNEjAia9ijGEWcyVisMTkRotMwgaFFoo328NPT1Fc5ieQ4NDjhRx53hTMh+LdF+P1x4dg6fF57D8HenQEEpSdElMUqJ3x/9WURlS5E5YCVKT7/Y/GUWJ0I0g/WVuAxZ7sX1W5YrqChFNTVmU7lGXbnOq6OtSlxqOqB1VW6kznUzvQSe/VIW97QY68iib+hN/iDZaIX8XN+A80UCSvKIH8fgMczTeKyQQPErI1Jr+Nv2y1LaGAJ+OzhZ/WbfAb5GX4tDp8rPXhjCQaHEjUzR5FW+2PQg/tsaraGvW5h6VbCoiTfUX4HMM05t8bCNAVECmFKSr6mu/LpevmTeYefZYj5cRMsb8H30O3dMuvAAAA//9Q7kFuuQIAAA
    objectset.rio.cattle.io/id: auth-prov-v2-roletemplate-local
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=RoleTemplate
    objectset.rio.cattle.io/owner-name: cluster-admin
    objectset.rio.cattle.io/owner-namespace: ''
rules:
- verbs:
  - '*'
  apiGroups:
  - <DOMAIN_551>
  resources:
  - clusters
  resourceNames:
  - local
apiVersion: <DOMAIN_776>/v1
kind: Role
