metadata:
  name: request-mnk27
  namespace: fleet-local
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 283c5a882dad3abad13b6e5ac6f9f4d5eafdff1e
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5RTS6vUMBT+K3LWTb2dPqYtuBAFFy6EUdyIi5PkZCY2TWoeIzjMf5fmPriKlXFTaML3ne9xcoGZIkqMCOMF0FoXMWpnw/rr+DcSMVAsvXalwBgNldq91BJGECaFSJ55OuoQfUZBsYlxPyx5djxPMIIyRPHZ3blCs5ywKl6811a+enPPfPgfYoszwQievicKkc122u1vAoUFBT1qYsYJNHAtQHjKgz/pmULEeYHRJmMKMMjJ5HT+dDGjxSOt0USf6B/DTxhOMMKur0WLfb+TKGvkKKuad9Si6NSgGtkSKqlURaucDXtbBgrIBg+kyJMVFGD8cgFc9GfyYY1zuwMogBsnpg8rwVsylOMfFZpABQhno3fGkH86mrRdPf+9tA3dKW9QfdcMe9khG/aKswZ5w3jdtUxVdVPVXKpq18L167UA7wwdSOUVXfQ779KysnIUJaZ4cl7/zBPLqQ+ldvCk6uAMbcm4FhDSfUU5ngfIR/JnLei1EC7ZuAFmN2n/vaDHB/OsqIdvhbXs9vIO+2FYDf8KAAD//40gObGVAwAA
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-mnk27
    objectset.rio.cattle.io/owner-namespace: fleet-local
subjects:
- kind: ServiceAccount
  name: request-mnk27-30497d6a-97fb-4ab4-b365-f13413bdf125
  namespace: cluster-fleet-local-local-1a3d67d0a899
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: request-mnk27
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
