metadata:
  name: local-cluster
  namespace: fleet-local
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 67f475f626e5473772f6084a291170a9de5942d1
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3SQQXObQAyF/4vOxF0whphbjJMmBDxjCG7jm7zIzpKFZRbZTerxf+9AZ9xecnyS3ic9naFCRojOgJ0qyJ7IxncQQVoITgs3zssqeVGLZb5JyqLcJmvxUOZjT3D87iZFmbn0vlquf2R2Kx6mRZkstkLH4PwDlnkKEeBjLuRjFqSftx9Z7M9Wyv+V1vfBarn+DQ6cUB8JInj9ueg2zeZTevq0q82hqu+fX70PV05zLdssiJU4XHVtnp/iu8PT95WWbd5tG13DxYGGGK+x2tYwsjJtP0izq0lyTzyxykwkMmuaKPNNVRDBXhPxzc4Y7tliN6CkpdH8ohrqGZsOovaotQMad6RH5Oj6D9VgiwcaeGyPBM6XO9+wf4MIgnDvh7N94AU088NpGHr7QNz66M1dNxQ4r2g2973KHc5psRmepI1EfSP1sWey8LfcdyjpGmKcgMvlTwAAAP//RVuWy+ABAAA
    objectset.rio.cattle.io/id: fleet-bootstrap
data:
  apiServerCA: <REDACTED:secret>
  apiServerURL: <REDACTED:secret>
  value: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
