metadata:
  name: default-token-8jl6c
  namespace: fleet-local
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 05c9db2a-5632-42a5-a280-bd5d204be24a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
