metadata:
  name: git-ml-ops
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: 805b2edc7580aa95fb4d7b3ad0bc3eadb9018dc2
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4SRT0vDQBDFv4rMOVuTtmn+gDfBgwehiBfxMDs7abfd7IbstB5KvrskaBWh7XF3HjO/994JWhY0KAj1CdD7ICg2+Dg+g94xSWSZ9TbMCEUcz2y4twZq2FjZBR0huSgLn557tTnuoYbGMcuf2TFD120xS+6erTcPT1bW3IWbyzy2DDW0ToXu9ulRHTsk/gFQLhA6GBKgniefr7blKNh2UPuDcwk41Oyuut9i3EINZZrrORsq8jJFrPJGL02hF2hSTQtGo6s0Kw3Nx2vf2Bsr6ox+CS6BCX7NDffsiSPU7yfAzr5xH23wV8KEBLQLtH8ZFzyyY5n0DbrICVDw0gfnuD9/7a0fq/xN/3++h6lqMzeaMEsVrjhXSyq0qlZUKE7LlKiqqgUXMHwMw1cAAAD//16EH2tOAgAA
    objectset.rio.cattle.io/id: gitjobs
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=GitRepo
    objectset.rio.cattle.io/owner-name: ml-ops
    objectset.rio.cattle.io/owner-namespace: fleet-local
secrets:
- name: git-ml-ops-token-t56g5
apiVersion: v1
kind: ServiceAccount
