metadata:
  name: request-4phx4
  namespace: fleet-default
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 83f9147ab5600ae075306279338a750fdd696b8a
  annotations:
    objectset.rio.cattle.io/applied: '{"metadata":{"name":"request-4phx4","namespace":"fleet-default","creationTimestamp":null,"labels":{"<DOMAIN_474>/managed":"true","<DOMAIN_553>/hash":"83f9147ab5600ae075306279338a750fdd696b8a"},"annotations":{"<DOMAIN_553>/id":"cluster-registration","<DOMAIN_553>/owner-gvk":"<DOMAIN_474>/v1alpha1,
      Kind=ClusterRegistration","<DOMAIN_553>/owner-name":"request-4phx4","<DOMAIN_553>/owner-namespace":"fleet-default"},"ownerReferences":[{"apiVersion":"<DOMAIN_474>/v1alpha1","kind":"ClusterRegistration","name":"request-4phx4","uid":"065dc95e-6f75-410f-9c18-07469903f9bc","controller":false,"blockOwnerDeletion":false}]},"rules":[{"verbs":["patch"],"apiGroups":["<DOMAIN_474>"],"resources":["clusters/status"],"resourceNames":["c-6tfcq"]}]}'
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-4phx4
    objectset.rio.cattle.io/owner-namespace: fleet-default
rules:
- verbs:
  - patch
  apiGroups:
  - <DOMAIN_474>
  resources:
  - clusters/status
  resourceNames:
  - c-6tfcq
apiVersion: <DOMAIN_776>/v1
kind: Role
