metadata:
  name: request-rl5k9
  namespace: fleet-default
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 74ee625e5a236418a5b7b7d002f6dbcdfb624713
  annotations:
    objectset.rio.cattle.io/applied: '{"metadata":{"name":"request-rl5k9","namespace":"fleet-default","creationTimestamp":null,"labels":{"<DOMAIN_474>/managed":"true","<DOMAIN_553>/hash":"74ee625e5a236418a5b7b7d002f6dbcdfb624713"},"annotations":{"<DOMAIN_553>/id":"cluster-registration","<DOMAIN_553>/owner-gvk":"<DOMAIN_474>/v1alpha1,
      Kind=ClusterRegistration","<DOMAIN_553>/owner-name":"request-rl5k9","<DOMAIN_553>/owner-namespace":"fleet-default"},"ownerReferences":[{"apiVersion":"<DOMAIN_474>/v1alpha1","kind":"ClusterRegistration","name":"request-rl5k9","uid":"815ca0dc-4bde-41b8-9a17-ff0b0c0f6b29","controller":false,"blockOwnerDeletion":false}]},"subjects":[{"kind":"ServiceAccount","name":"request-rl5k9-815ca0dc-4bde-41b8-9a17-ff0b0c0f6b29","namespace":"cluster-fleet-default-c-4rxd5-8e688ca84c6e"}],"roleRef":{"apiGroup":"<DOMAIN_776>","kind":"Role","name":"request-rl5k9"}}'
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-rl5k9
    objectset.rio.cattle.io/owner-namespace: fleet-default
subjects:
- kind: ServiceAccount
  name: request-rl5k9-815ca0dc-4bde-41b8-9a17-ff0b0c0f6b29
  namespace: cluster-fleet-default-c-4rxd5-8e688ca84c6e
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: request-rl5k9
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
