metadata:
  name: request-sfqxn
  namespace: fleet-default
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 5f8adf9c5bd4bfb836c22353684861477f94d4b5
  annotations:
    objectset.rio.cattle.io/applied: '{"metadata":{"name":"request-sfqxn","namespace":"fleet-default","creationTimestamp":null,"labels":{"<DOMAIN_474>/managed":"true","<DOMAIN_553>/hash":"5f8adf9c5bd4bfb836c22353684861477f94d4b5"},"annotations":{"<DOMAIN_553>/id":"cluster-registration","<DOMAIN_553>/owner-gvk":"<DOMAIN_474>/v1alpha1,
      Kind=ClusterRegistration","<DOMAIN_553>/owner-name":"request-sfqxn","<DOMAIN_553>/owner-namespace":"fleet-default"},"ownerReferences":[{"apiVersion":"<DOMAIN_474>/v1alpha1","kind":"ClusterRegistration","name":"request-sfqxn","uid":"2fe14f07-695d-481c-bee6-370545ce3c5c","controller":false,"blockOwnerDeletion":false}]},"subjects":[{"kind":"ServiceAccount","name":"request-sfqxn-2fe14f07-695d-481c-bee6-370545ce3c5c","namespace":"cluster-fleet-default-c-79qgb-96c374c00b58"}],"roleRef":{"apiGroup":"<DOMAIN_776>","kind":"Role","name":"request-sfqxn"}}'
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-sfqxn
    objectset.rio.cattle.io/owner-namespace: fleet-default
subjects:
- kind: ServiceAccount
  name: request-sfqxn-2fe14f07-695d-481c-bee6-370545ce3c5c
  namespace: cluster-fleet-default-c-79qgb-96c374c00b58
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: request-sfqxn
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
