metadata:
  name: crt-<COMPANY>-stg-cluster-owner
  namespace: fleet-default
  labels:
    objectset.rio.cattle.io/hash: bc9b6cf6f4bbe1c2dae273cb3bf3089f57a479d7
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7xRTY/TMBD9K2iOKC5pm22aSJw4cEDisFpxQT2MnXFr1h+RPQ6HKv8dOSwlQipw2ps9H++9ee8KjhgHZIT+Cuh9YGQTfCrfIL+R4kS8iSZsFDJb2pjwzgzQA2a+iDGGSUw7EYMlJjdaZBJpckokPkN1FyF89xTFeXqGHhx6PJMjz6uBaV+9+WT88P4xWHp6Qf4noEdH0IOyOTFFsRT/aymNqMomzBWoSIsFT8ZRYnQj9D5bW4FFSfavxlwwXaAHqTp5UPqgGylpq3YD0q7dK7mXel8fO/3QYtN2Q1vYfkmOfPNN/Kl/rVBbIhYDacyWy21l5pE0RfKKEvRfr4Cj+UIxmeChhxKRKW/jz2uDt1DBs/Elyg8/+eCmZpVgXsLeyrrDw3ErhmN3FA21UnStVAIfdFOrQ1OruoH5NFcQs/2t4mMMeSy/OyrgVEGkFHJU9LkcWUZv5Kvm0nixJZXGRFEuxbdwmqvXJDvNPwIAAP//ltpWRTQDAAA
    objectset.rio.cattle.io/id: auth-prov-v2-roletemplate-<COMPANY>-stg
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=RoleTemplate
    objectset.rio.cattle.io/owner-name: cluster-owner
    objectset.rio.cattle.io/owner-namespace: ''
rules:
- verbs:
  - '*'
  apiGroups:
  - <DOMAIN_551>
  resources:
  - clusters
  resourceNames:
  - <COMPANY>-stg
- verbs:
  - '*'
  apiGroups:
  - <DOMAIN_551>
  resources:
  - clusters
  resourceNames:
  - <COMPANY>-stg
apiVersion: <DOMAIN_776>/v1
kind: Role
