metadata:
  name: crt-<COMPANY>-stg-cluster-member
  namespace: fleet-default
  labels:
    objectset.rio.cattle.io/hash: e20717c73261c415edfbe008d6119b5c546e5d85
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xRO4/UMBD+K2jqeEn28tpIVBQUSBSnEw3aYuxMsub8iOxxrljlvyMvxxIJHdB5PI/vdQVLjCMywnAFdM4zsvYu5tLL76Q4Eh+C9geFzIYO2r/XIwyAiS9iCX4V61EEb4jJLgaZRFytEpFnKN684F8cBTGvzzCARYczWXK8G1gfineftRs/PHpDT6+X/3nQoSUYQJkUmYKwZCWF/9qKC6q8ClsBKtDNgydtKTLaBQaXjCnAoCTzV2cuGC8wAB3LrupU93BsK1VXDY2TpLLsx7aqTrJRTd1SM/ZNRvvFOfDdOPGHgD3FyRCxGGnCZDiLyyIeaaJATlGE4dsVcNFfKUTtHQyQQ9L5rd28t7iCAp61y2F+/AkIdzq7DNMt7kqWJ2z7Soz9qRc1dVKcOqkENlNdqrYuVVnDdt4KCMn8ZvEp+LTk6g0WcC4gUPQpKPqSRebRO/iueWu8+hJzY6Ugb58zZRdekNUFztt5+xEAAP//ESMFLdMCAAA
    objectset.rio.cattle.io/id: auth-prov-v2-roletemplate-<COMPANY>-stg
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=RoleTemplate
    objectset.rio.cattle.io/owner-name: cluster-member
    objectset.rio.cattle.io/owner-namespace: ''
rules:
- verbs:
  - get
  - watch
  apiGroups:
  - <DOMAIN_551>
  resources:
  - clusters
  resourceNames:
  - <COMPANY>-stg
apiVersion: <DOMAIN_776>/v1
kind: Role
