metadata:
  name: request-pq7rc
  namespace: fleet-default
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 5890742908affac4deece1718e3a713b3f2b5c24
  annotations:
    objectset.rio.cattle.io/applied: '{"metadata":{"name":"request-pq7rc","namespace":"fleet-default","creationTimestamp":null,"labels":{"<DOMAIN_474>/managed":"true","<DOMAIN_553>/hash":"5890742908affac4deece1718e3a713b3f2b5c24"},"annotations":{"<DOMAIN_553>/id":"cluster-registration","<DOMAIN_553>/owner-gvk":"<DOMAIN_474>/v1alpha1,
      Kind=ClusterRegistration","<DOMAIN_553>/owner-name":"request-pq7rc","<DOMAIN_553>/owner-namespace":"fleet-default"},"ownerReferences":[{"apiVersion":"<DOMAIN_474>/v1alpha1","kind":"ClusterRegistration","name":"request-pq7rc","uid":"3ac30074-a990-46e1-9807-338bbe7f59a1","controller":false,"blockOwnerDeletion":false}]},"subjects":[{"kind":"ServiceAccount","name":"request-pq7rc-3ac30074-a990-46e1-9807-338bbe7f59a1","namespace":"cluster-fleet-default-c-chr6h-8e6624036fde"}],"roleRef":{"apiGroup":"<DOMAIN_776>","kind":"Role","name":"request-pq7rc"}}'
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-pq7rc
    objectset.rio.cattle.io/owner-namespace: fleet-default
subjects:
- kind: ServiceAccount
  name: request-pq7rc-3ac30074-a990-46e1-9807-338bbe7f59a1
  namespace: cluster-fleet-default-c-chr6h-8e6624036fde
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: request-pq7rc
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
