metadata:
  name: request-vd5gr
  namespace: fleet-default
  labels:
    fleet.cattle.io/managed: 'true'
    objectset.rio.cattle.io/hash: 92ee53bf47edbc990ad0962a2bb09e4aac5c039e
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5RTTY/TMBD9K2jOcUjTJm0icUAgceCAVBAXxGFsv7Smrh38UaSt+t9RsuyKRQQtR9t6b97H+EpnJNacmPorsXM+cTLexeno5TeoFJHKYHypOCWL0viXRlNPyuaYEETAwcQUZhQVixj/wyGIw+VEPQ0WSL+9XVZsxyOvihfvjdOv3twz7/+H2PEZ1FPA94yYxEU3h/AsUBxZ4UGT0Bg420S3glTAPPqTOSMmPo/Uu2xtQZYl7JzPnz7O7PiAKZwUMv4x/sjxSD11NdCs5bDZQkvVdRXrqmtrrqWsOmyYVaOqdYdJzoLBZQsFzSb3GBDgFCL1X67Eo/mMEKdIl3uggqT16vRhIngLi7mCfmAbUZDyLgVvLcLj1cm4yfXfi1tQnuctanaV7PROC9Y1i029HQR3shNys1Xdut2uqqGm29dbQcFb7DHMazqad8HncWKVrErO6eiDuZsnlqddLI2nR1V7b7Ek41ZQzPclzfH8gnxEuBiF10r57NICWDxL+9OKHj7Nk6qEEq6901E0vG2kbIe2XbeT6Z8BAAD//y0oNA+dAwAA
    objectset.rio.cattle.io/id: cluster-registration
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_474>/v1alpha1, Kind=ClusterRegistration
    objectset.rio.cattle.io/owner-name: request-vd5gr
    objectset.rio.cattle.io/owner-namespace: fleet-default
subjects:
- kind: ServiceAccount
  name: request-vd5gr-580b9d8d-ad2a-427f-a9b9-b47c936710f2
  namespace: cluster-fleet-default-c-n6zds-5a75bb6f6636
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: request-vd5gr
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
