metadata:
  name: default-token-gd8nx
  namespace: fleet-default
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: bab24d66-be0a-4c69-8d4a-20c8759ba1b1
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
