metadata:
  name: fleet-controller
  namespace: cattle-fleet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fleet
    meta.helm.sh/release-namespace: cattle-fleet-system
data:
  config: "{\n  \"systemDefaultRegistry\": \"\",\n  \"agentImage\": \"rancher/fleet-agent:v0.15.2\"\
    ,\n  \"agentImagePullPolicy\": \"IfNotPresent\",\n  \"apiServerURL\": \"https://<DOMAIN_8>.<COMPANY_DOMAIN>\"\
    ,\n  \"apiServerCA\": \"\",\n  \"agentCheckinInterval\": \"15m\",\n  \"agentTLSMode\"\
    : \"strict\",\n  \"agentWorkers\": {\n        \"bundledeployment\": \"50\",\n\
    \        \"drift\": \"50\"\n  },\n  \n  \"garbageCollectionInterval\": \"15m\"\
    ,\n  \n  \"ignoreClusterRegistrationLabels\": false,\n  \"bootstrap\": {\n   \
    \ \"paths\": \"\",\n    \"repo\": \"\",\n    \"secret\": \"\",\n    \"clusterLabels\"\
    : {},\n    \"branch\":  \"master\",\n    \"namespace\": \"fleet-local\",\n   \
    \ \"agentNamespace\": \"cattle-fleet-local-system\"\n  },\n  \"webhookReceiverURL\"\
    : \"\",\n  \"githubURLPrefix\": \"\",\n  \"gitClientTimeout\": \"30s\"\n}\n"
apiVersion: v1
kind: ConfigMap
