metadata:
  name: helmops
  namespace: cattle-fleet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fleet
    meta.helm.sh/release-namespace: cattle-fleet-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmops
  template:
    metadata:
      labels:
        app: helmops
        fleet.cattle.io/shard-default: 'true'
        fleet.cattle.io/shard-id: ''
    spec:
      volumes:
      - name: tmp
        emptyDir: {}
      containers:
      - name: helmops
        image: rancher/fleet:v0.15.2
        args:
        - fleetcontroller
        - helmops
        ports:
        - name: metrics
          containerPort: 8081
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_72>
        - name: CATTLE_ELECTION_LEASE_DURATION
          value: 30s
        - name: CATTLE_ELECTION_RETRY_PERIOD
          value: 10s
        - name: CATTLE_ELECTION_RENEW_DEADLINE
          value: 25s
        - name: HELMOPS_RECONCILER_WORKERS
          value: '50'
        resources: {}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: helmops
      serviceAccount: helmops
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      schedulerName: default-scheduler
      tolerations:
      - key: <DOMAIN_96>/os
        operator: Equal
        value: linux
        effect: NoSchedule
      priorityClassName: rancher-critical
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
