metadata:
  name: helmops
  namespace: cattle-fleet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fleet
    meta.helm.sh/release-namespace: cattle-fleet-system
subjects:
- kind: ServiceAccount
  name: helmops
roleRef:
  apiGroup: <DOMAIN_1>
  kind: Role
  name: helmops
apiVersion: <DOMAIN_1>/v1
kind: RoleBinding
