metadata:
  name: postgres
  namespace: keycloak
  labels:
    app: postgres
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-data
        emptyDir: {}
      containers:
      - name: postgres
        image: <DOMAIN_30>.<COMPANY_DOMAIN>/postgres/postgres:17
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: <REDACTED:env>
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_LOG_STATEMENT
          value: all
        resources: {}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
