metadata:
  name: postgres
  namespace: keycloak
  labels:
    app: postgres
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  clusterIP: <IP_28>
  clusterIPs:
  - <IP_28>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
apiVersion: v1
kind: Service
