metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
  annotations: {}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: <DOMAIN_30>.<COMPANY_DOMAIN>/keycloak/keycloak:26.7.0
        args:
        - start
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: jgroups
          containerPort: 7800
          protocol: TCP
        - name: jgroups-fd
          containerPort: 57800
          protocol: TCP
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: <REDACTED:env>
        - name: KC_PROXY_HEADERS
          value: xforwarded
        - name: KC_HTTP_ENABLED
          value: 'true'
        - name: KC_HOSTNAME_STRICT
          value: 'false'
        - name: KC_HEALTH_ENABLED
          value: 'true'
        - name: KC_CACHE
          value: ispn
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_71>
        - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
          value: $(POD_IP)
        - name: KC_DB_URL_DATABASE
          value: <REDACTED:env>
        - name: KC_DB_URL_HOST
          value: <REDACTED:env>
        - name: KC_DB
          value: postgres
        - name: KC_DB_PASSWORD
          value: <REDACTED:env>
        - name: KC_DB_USERNAME
          value: keycloak
        resources:
          limits:
            cpu: '2'
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 1700Mi
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9000
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/started
            port: 9000
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 1
          successThreshold: 1
          failureThreshold: 600
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: keycloak-discovery
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 1
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
apiVersion: apps/v1
kind: StatefulSet
