metadata:
  name: default-token-279d9
  namespace: knox2fem
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 8599cb97-e69c-420b-8c71-5030844a55c1
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
