metadata:
  name: default-token-2h7m6
  namespace: u-ulqmnp7jyh
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: dc2506c9-4a82-4a27-b52c-b51d3ce852ee
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
