metadata:
  name: default-token-vlh7p
  namespace: u-q79r7
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 21c3d06f-9ed9-4a76-93d6-9a4a0d39a781
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
