metadata:
  name: loki
  namespace: svms
  labels:
    app: loki
  annotations: {}
subjects:
- kind: ServiceAccount
  name: loki
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: loki
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
