metadata:
  name: promtail-token-vq5ph
  namespace: svms
  annotations:
    kubernetes.io/service-account.name: promtail
    kubernetes.io/service-account.uid: 018302e6-23f2-45b1-aa64-97a46ec16c99
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
