metadata:
  name: default-token-fkqln
  namespace: svms
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 6c1fb198-990c-4fbd-b12e-627d05db9e4e
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
