metadata:
  name: influxdb2-token-s2fdm
  namespace: svms
  annotations:
    kubernetes.io/service-account.name: influxdb2
    kubernetes.io/service-account.uid: 22739870-bcc5-4d29-9b16-b320a5ba0e79
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
