metadata:
  name: percona-service
  namespace: svms
  labels:
    app: percona
    chart: pmm-server-2.26.1
    component: pmm
    heritage: Helm
    release: percona
  annotations: {}
spec:
  ports:
  - name: https
    protocol: TCP
    port: 23443
    targetPort: 443
  selector:
    app: percona
    component: pmm
  clusterIP: <IP_123>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
