metadata:
  name: mysql-grafana-svc
  namespace: svms
  labels:
    app: mysql-grafana-svc
  annotations: {}
spec:
  ports:
  - name: mysql-grafana
    protocol: TCP
    port: 13306
    targetPort: 3306
  - name: mysql-exporter-grafana
    protocol: TCP
    port: 9104
    targetPort: 9104
  selector:
    app: mysql-grafana
  clusterIP: <IP_122>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
