metadata:
  name: default-token-vzq9f
  namespace: u-xdqo56ujck
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: f0895491-a38c-42fa-86bd-a32e1e8d41fa
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
