metadata:
  name: default-token-6ljgq
  namespace: u-s3wceu2qkb
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 413de6bb-421f-4d94-bae7-aedc6361dfec
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
