metadata:
  name: request-d9t9m-887f6417-a513-4fe1-928a-0f9fb5bd65a2-token-lsrzt
  namespace: cluster-fleet-local-local-1a3d67d0a899
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: request-d9t9m-887f6417-a513-4fe1-928a-0f9fb5bd65a2
    kubernetes.io/service-account.uid: d8326833-1ab0-4f43-996c-32a842d7fe1b
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
