metadata:
  name: shift-handover-image-shift-handover-backend-0
  namespace: shift-handover
  labels:
    app: shift-handover-backend
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_52>
    volume.kubernetes.io/storage-provisioner: <DOMAIN_52>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: pvc-ec67ac19-742e-47a1-927c-873861737830
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
