metadata:
  name: fe-secret
  namespace: shift-handover
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: f6c18b7826d97af6598f63b54624be8cc919b4f4
  annotations:
    meta.helm.sh/release-name: shift-handover
    meta.helm.sh/release-namespace: shift-handover
    objectset.rio.cattle.io/id: default-shift-handover-cattle-fleet-local-system
data:
  REACT_APP_API_URL: <REDACTED:secret>
  REACT_APP_FRONTEND_URL: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
