metadata:
  name: shift-handover-backend
  namespace: shift-handover
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: f6c18b7826d97af6598f63b54624be8cc919b4f4
  annotations:
    meta.helm.sh/release-name: shift-handover
    meta.helm.sh/release-namespace: shift-handover
    objectset.rio.cattle.io/id: default-shift-handover-cattle-fleet-local-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shift-handover-backend
  template:
    metadata:
      labels:
        app: shift-handover-backend
    spec:
      containers:
      - name: shift-handover-be
        image: <DOMAIN_30>.<COMPANY_DOMAIN>/shift-handover/backend/main:10
        env:
        - name: MONGODB_DB_NAME
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: MONGODB_DB_NAME
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: MONGODB_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: SECRET_KEY
        - name: KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: KEYCLOAK_CLIENT_SECRET
        - name: CIP_KEYCLOAK_BASE_URL
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: CIP_KEYCLOAK_BASE_URL
        - name: CIP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: CIP_CLIENT_ID
        - name: CIP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: CIP_CLIENT_SECRET
        - name: CIP_BASE_URL
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: CIP_BASE_URL
        resources:
          limits:
            cpu: '1'
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - name: shift-handover-image
          mountPath: /app/images
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: shift-handover-image
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: rook-ceph-block
      volumeMode: Filesystem
  serviceName: shift-handover-backend
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 1
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
apiVersion: apps/v1
kind: StatefulSet
