metadata:
  name: default-token-kq9vn
  namespace: u-p7vaiakhge
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 2153865a-fd5c-4820-a6ec-d07a69a14f81
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
