metadata:
  name: default-token-hjngn
  namespace: u-zoriiln52e
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 3636952a-b3e8-4940-ac9e-17b33e96bf5a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
