metadata:
  name: event-manage-db-data-event-manage-db-0
  namespace: event-management
  labels:
    app: event-manage-db
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_529>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-aae9a95f-18a6-4d5f-9a51-678216ce06d4
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
