metadata:
  name: be-secret
  namespace: event-management
data:
  DB_HOST: <REDACTED:secret>
  EMAIL_CLIENT_ID: <REDACTED:secret>
  EMAIL_CLIENT_SECRET: <REDACTED:secret>
  MESSENGER_CLIENT_ID: <REDACTED:secret>
  MESSENGER_CLIENT_SECRET: <REDACTED:secret>
  SECRET_KEY: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
