metadata:
  name: passbolt-view
  namespace: passbolt
  annotations: {}
subjects:
- kind: ServiceAccount
  name: passbolt
  namespace: passbolt
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: passbolt-full-access
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
