metadata:
  name: passbolt-full-access
  namespace: passbolt
  annotations: {}
rules:
- verbs:
  - '*'
  apiGroups:
  - ''
  - extensions
  - apps
  resources:
  - '*'
- verbs:
  - '*'
  apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
apiVersion: <DOMAIN_776>/v1
kind: Role
