metadata:
  name: mysql-root-password
  namespace: passbolt
  labels:
    app.kubernetes.io/instance: mysql-passbolt-prd
  annotations: {}
data:
  password: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
