metadata:
  name: default-token-snfbd
  namespace: u-72uggsypy6
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 5052ff2a-4ae7-46e2-a5f6-d985e24a74cc
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
