metadata:
  name: default-token-mdsbg
  namespace: acs
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: f7bb5c99-c4cd-406b-8c05-225615017e8d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
