metadata:
  name: acs-fe-expose
  namespace: acs
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: acs-fe
  clusterIP: <IP_33>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_40>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
