metadata:
  name: acs-backend-service
  namespace: acs
  labels:
    app: acs-backend
  annotations: {}
spec:
  ports:
  - name: acs-backend
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: acs-backend
  clusterIP: <IP_32>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
