metadata:
  name: default-token-77lv2
  namespace: u-qzbn6m3mqd
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: c3f08a54-7924-482d-bd34-45e71f106c92
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
