metadata:
  name: default-token-nczcl
  namespace: u-taswvbmwbk
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 63a78f7a-9a55-493b-aa9c-e8ef43ec36fe
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
