metadata:
  name: default-token-lvrn4
  namespace: u-wujwy735wz
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: a5fefa50-c636-4a39-832c-888dbdc3fe5b
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
