metadata:
  name: okr-fe-expose
  namespace: okr
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 49222
    targetPort: 80
  selector:
    app: okr-frontend
  clusterIP: <IP_89>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
