metadata:
  name: okr-redis-service
  namespace: okr
  labels:
    app: okr-redis
  annotations: {}
spec:
  ports:
  - name: okr-redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: okr-redis
  clusterIP: <IP_92>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
