metadata:
  name: okr-be-expose
  namespace: okr
  labels:
    app.kubernetes.io/instance: okr-backend
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 49206
    targetPort: 8080
  selector:
    app: okr-backend
  clusterIP: <IP_88>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
