metadata:
  name: artifact-repositories
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: "archiveLogs: true\ns3:\n  bucket: my-bucket\n  endpoint: minio:9000\n\
    \  insecure: true\n  accessKeySecret:\n    name: my-minio-cred\n    key: accesskey\n\
    \  secretKeySecret:\n    name: my-minio-cred\n    key: secretkey\n"
  empty: ''
  my-key: "archiveLogs: true\ns3:\n  bucket: my-bucket\n  endpoint: minio:9000\n \
    \ insecure: true\n  accessKeySecret:\n    name: my-minio-cred\n    key: accesskey\n\
    \  secretKeySecret:\n    name: my-minio-cred\n    key: secretkey\n"
apiVersion: v1
kind: ConfigMap
