metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations: {}
data:
  accounts.ops: login
  accounts.ops.enabled: 'true'
  accounts.passbolt-admin: <REDACTED:env>
  accounts.passbolt-admin.enabled: <REDACTED:env>
  accounts.passbolt-ops: <REDACTED:env>
  accounts.passbolt-ops.enabled: <REDACTED:env>
  dex.config: "connectors:\n- type: github\n  id: sec-github\n  name: Github SEC\n\
    \  config:\n    hostName: <DOMAIN_9>\n    clientID: 80f9da07f7161a9eadc2\n   \
    \ clientSecret: $<DOMAIN_10>\n    orgs:\n    - name: <COMPANY>-sre\n"
  repositories: "- passwordSecret:\n    key: password\n    name: github-sec\n  url:\
    \ https://<DOMAIN_9>/lam-dv1/<DOMAIN_11>\n  usernameSecret:\n    key: username\n\
    \    name: github-sec\n- passwordSecret:\n    key: password\n    name: github-sec\n\
    \  url: https://<DOMAIN_9>/<COMPANY>-sre/<DOMAIN_12>\n  usernameSecret:\n    key:\
    \ username\n    name: github-sec\n- passwordSecret:\n    key: password\n    name:\
    \ github-sec\n  url: https://<DOMAIN_9>/<COMPANY>-sre/<DOMAIN_13>\n  usernameSecret:\n\
    \    key: username\n    name: github-sec\n"
  url: http://argocd.<COMPANY><DOMAIN_14>/
apiVersion: v1
kind: ConfigMap
