metadata:
  name: ci-example-tbgbc-workdir
  namespace: argocd
  labels:
    workflows.argoproj.io/workflow: ci-example-tbgbc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
