metadata:
  name: submit-workflow-template
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
rules:
- verbs:
  - list
  apiGroups:
  - <DOMAIN_777>
  resources:
  - workfloweventbindings
- verbs:
  - get
  apiGroups:
  - <DOMAIN_777>
  resources:
  - workflowtemplates
- verbs:
  - create
  apiGroups:
  - <DOMAIN_777>
  resources:
  - workflows
apiVersion: <DOMAIN_776>/v1
kind: Role
