metadata:
  name: <DOMAIN_16>
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
subjects:
- kind: ServiceAccount
  name: <DOMAIN_16>
  namespace: argo
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: submit-workflow-template
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
