metadata:
  name: argo-server-role
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
rules:
- verbs:
  - get
  - watch
  - list
  apiGroups:
  - ''
  resources:
  - configmaps
- verbs:
  - get
  - create
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - secrets
- verbs:
  - get
  - list
  - watch
  - delete
  apiGroups:
  - ''
  resources:
  - pods
  - pods/exec
  - pods/log
- verbs:
  - watch
  - create
  - patch
  apiGroups:
  - ''
  resources:
  - events
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - serviceaccounts
- verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  apiGroups:
  - <DOMAIN_777>
  resources:
  - eventsources
  - sensors
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - cronworkflows
  - cronworkflows/finalizers
apiVersion: <DOMAIN_776>/v1
kind: Role
