metadata:
  name: agent
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations:
    workflows.argoproj.io/description: 'This is the minimum recommended permissions
      needed if you want to use the agent, e.g. for HTTP or plugin templates.


      If <= v3.2 you must replace `workflowtasksets/status` with `patch workflowtasksets`.

      '
rules:
- verbs:
  - list
  - watch
  apiGroups:
  - <DOMAIN_777>
  resources:
  - workflowtasksets
- verbs:
  - patch
  apiGroups:
  - <DOMAIN_777>
  resources:
  - workflowtasksets/status
apiVersion: <DOMAIN_776>/v1
kind: Role
