metadata:
  name: my-minio-cred
  namespace: argocd
  labels:
    app: minio
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
data:
  accesskey: <REDACTED:secret>
  secretkey: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
