metadata:
  name: argocd-application-controller-token-mwkg4
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argocd-application-controller
    kubernetes.io/service-account.uid: fef52792-dc53-4f07-9959-3cc8a72b519c
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
