metadata:
  name: <DOMAIN_16>-token-qsphr
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: <DOMAIN_16>
    kubernetes.io/service-account.uid: 98e6bdb0-4811-4036-bd45-c669da0c717f
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
