metadata:
  name: default-token-7dxrf
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 29e1f313-f115-456c-bbad-01c9bcbee414
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
