metadata:
  name: github-sec
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
  annotations: {}
data:
  password: <REDACTED:secret>
  username: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
