metadata:
  name: repo-3221240478
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: <REDACTED:env>
  annotations:
    managed-by: <DOMAIN_549>
data:
  password: <REDACTED:secret>
  project: <REDACTED:secret>
  tlsClientCertKey: <REDACTED:secret>
  type: <REDACTED:secret>
  url: <REDACTED:secret>
  username: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
