metadata:
  name: argo-token-jwnb9
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argo
    kubernetes.io/service-account.uid: 287adda9-43a8-4c31-a8b1-5634ebbb1558
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
