metadata:
  name: argocd-notifications-controller-token-958v6
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argocd-notifications-controller
    kubernetes.io/service-account.uid: 6ad51b8d-fc58-40b2-880e-25b8d061cb7e
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
