metadata:
  name: argo-postgres-config
  namespace: argocd
  labels:
    app: postgres
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
data:
  password: <REDACTED:secret>
  username: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
