metadata:
  name: argo-server-sso
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
data:
  clientID: <REDACTED:secret>
  clientSecret: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
