metadata:
  name: argocd-notifications-controller
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
  annotations: {}
secrets:
- name: argocd-notifications-controller-token-958v6
apiVersion: v1
kind: ServiceAccount
