metadata:
  name: <DOMAIN_16>
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd-workflow
  annotations: {}
secrets:
- name: <DOMAIN_16>-token-qsphr
apiVersion: v1
kind: ServiceAccount
