metadata:
  name: feedback360-db-postgresql-0
  namespace: feedback360
  labels:
    app: postgresql
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_529>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-5a442e65-2667-4b08-8c92-c75b8693527d
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
