metadata:
  name: mongodb-secret
  namespace: feedback360
  annotations: {}
data:
  DB_HOST: <REDACTED:secret>
  DB_NAME: <REDACTED:secret>
  DB_PASSWORD: <REDACTED:secret>
  DB_PORT: <REDACTED:secret>
  DB_USERNAME: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
