metadata:
  name: default-token-tfw94
  namespace: feedback360
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: ce414cdb-8316-45e9-b5f6-0bb87c6a5e0d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
