metadata:
  name: default-token-5n4jp
  namespace: u-vhxck
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 07e07c24-910f-441c-8f56-0552a3dd8c73
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
