metadata:
  name: default-token-kvg5c
  namespace: artifactory
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 9f96e53a-9937-472d-b6d6-8f6828b2e9cf
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
