metadata:
  name: default-token-fzlfx
  namespace: portal
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: f9f987d0-5661-4583-85e7-3f13865c52ff
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
