metadata:
  name: <DOMAIN_550>-agent-local.v22
  namespace: cattle-fleet-local-system
  labels:
    modifiedAt: '1659076468'
    name: fleet-agent-local
    owner: helm
    version: '22'
data:
  release: <REDACTED:secret>
type: <DOMAIN_152>/release.v1
apiVersion: v1
kind: Secret
