metadata:
  name: default-token-kq7pz
  namespace: cattle-fleet-local-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: b0ca48c0-beab-4f8f-9078-8287e1b51057
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
