metadata:
  name: fleet-agent
  namespace: cattle-fleet-local-system
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: 362023f752e7f1989d8b652e029bd2c658ae7c44
  annotations:
    meta.helm.sh/release-name: fleet-agent-local
    meta.helm.sh/release-namespace: cattle-fleet-local-system
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOPW7DMAxG78LZchMl/t16hgLdKZpu1MqiYbIBiiB3LwRPWTyS78PDewCu8ZM3jZJhhPsZKviJeYIRPni7R+J3IvnNBhUsbDihIYwPwJzF0KJkLaeEbyZTtnqLUhOaJa6jvMUimhOzOfzibC6ImNqGq9tHbodJCJPTPzVe4FlBwsDp0HxDvcEIl9af/GXuGs/dfB76YepD23g++SFMntqmR+7oei3SjAu/5sD+1BWpkIOk538AAAD//3vISu8pAQAA
    objectset.rio.cattle.io/id: fleet-agent-bootstrap-cattle-fleet-local-system
secrets:
- name: fleet-agent-token-b9n4l
apiVersion: v1
kind: ServiceAccount
