metadata:
  name: kubernetes
  namespace: default
  labels:
    component: apiserver
    provider: kubernetes
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 6443
  clusterIP: <IP_58>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
