metadata:
  name: cluster-api-operator-resources-cleanup-script
  namespace: cattle-turtles-system
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-weight: '1'
data:
  cleanup.sh: "#!/usr/bin/env bash\n\nset -euo pipefail\n\nremove_finalizers_and_delete()\
    \ {\n  local resource_type=\"$1\"\n  if kubectl get crd $resource_type > /dev/null\
    \ 2>&1; then\n    kubectl get $resource_type --all-namespaces --no-headers --ignore-not-found\
    \ | awk '{print $1 \" \" $2}' | xargs -r -n2 bash -c 'kubectl patch '\"${resource_type}\"\
    ' \"$1\" -n \"$0\" --type merge -p \"{\\\"metadata\\\":{\\\"finalizers\\\":null}}\"\
    '\n    kubectl delete $resource_type --all --all-namespaces\n  else\n    echo\
    \ \"Resource type $resource_type does not exist, skipping cleanup.\"\n  fi\n}\n\
    \nresource_types=(\n  \"<DOMAIN_15>\"\n  \"<DOMAIN_16>\"\n  \"<DOMAIN_17>\"\n\
    \  \"<DOMAIN_18>\"\n  \"<DOMAIN_19>\"\n  \"<DOMAIN_20>\"\n  \"<DOMAIN_21>\"\n\
    )\n\nfor resource_type in \"${resource_types[@]}\"; do\n  remove_finalizers_and_delete\
    \ \"$resource_type\"\ndone\n"
apiVersion: v1
kind: ConfigMap
