metadata:
  name: rancher-turtles-leader-election-rolebinding
  namespace: cattle-turtles-system
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rancher-turtles
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: rancher-turtles
  annotations:
    meta.helm.sh/release-name: rancher-turtles
    meta.helm.sh/release-namespace: cattle-turtles-system
subjects:
- kind: ServiceAccount
  name: rancher-turtles-manager
  namespace: cattle-turtles-system
roleRef:
  apiGroup: <DOMAIN_1>
  kind: Role
  name: rancher-turtles-leader-election-role
apiVersion: <DOMAIN_1>/v1
kind: RoleBinding
