metadata:
  name: default-token-sdpck
  namespace: actions-runner
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 984cbee9-adfc-4ef5-84a0-0ae0a03b7ab5
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
