metadata:
  name: mongodb-auto-backup-1784052000
  namespace: shift-handover
  labels:
    controller-uid: 60927c5a-39bf-4422-ad60-f42069923dfb
    job-name: mongodb-auto-backup-1784052000
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  selector:
    matchLabels:
      controller-uid: 60927c5a-39bf-4422-ad60-f42069923dfb
  template:
    metadata:
      labels:
        controller-uid: 60927c5a-39bf-4422-ad60-f42069923dfb
        job-name: mongodb-auto-backup-1784052000
    spec:
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: mongodb-backup-pvc
      containers:
      - name: backup
        image: artifactory.<COMPANY><DOMAIN_14>:30807/docker-local/fb360/base-images/mongo:6.0.5
        command:
        - /bin/sh
        - -c
        - "TIMESTAMP=$(date +%Y%m%d-%H%M%S)\nBACKUP_DIR=\"/backup/backup-$TIMESTAMP\"\
          \n\necho \"Starting MongoDB backup at $(date)\"\n\nmongodump \\\n  --host\
          \ mongodb:27017 \\\n  --username admin \\\n  --password admin \\\n  --authenticationDatabase\
          \ admin \\\n  --out $BACKUP_DIR\n\necho \"Backup completed\"\nls -la $BACKUP_DIR/\n"
        resources: {}
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
      - name: secret-registry-image
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: <DOMAIN_138>/hostname
                operator: In
                values:
                - <CLEANUP_HOST_4>
      schedulerName: default-scheduler
apiVersion: batch/v1
kind: Job
