metadata:
  name: shift-handover-image-shift-handover-backend-0
  namespace: shift-handover
  labels:
    app: shift-handover-backend
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_529>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: pvc-8c18e128-c76d-4a84-a6a6-67835a9201f0
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
