metadata:
  name: be-secret
  namespace: shift-handover
data:
  CIP_BASE_URL: <REDACTED:secret>
  CIP_CLIENT_ID: <REDACTED:secret>
  CIP_CLIENT_SECRET: <REDACTED:secret>
  CIP_KEYCLOAK_BASE_URL: <REDACTED:secret>
  KEYCLOAK_CLIENT_ID: <REDACTED:secret>
  KEYCLOAK_CLIENT_SECRET: <REDACTED:secret>
  KEYCLOAK_REALM: <REDACTED:secret>
  KEYCLOAK_URL: <REDACTED:secret>
  MONGODB_DB_NAME: <REDACTED:secret>
  MONGODB_URI: <REDACTED:secret>
  SECRET_KEY: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
