metadata:
  name: default-token-tk7ml
  namespace: shift-handover
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: d3be3eb6-6a94-4d0c-a4a7-e9c2442b1e76
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
