metadata:
  name: default-token-tjdc5
  namespace: u-opuz4wfoda
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 19d395a4-9262-46cd-b04b-8d0e02acb48a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
