metadata:
  name: cattle-impersonation-u-mo773yttt4-token-d9l9n
  namespace: cattle-impersonation-system
  annotations:
    kubernetes.io/service-account.name: cattle-impersonation-u-mo773yttt4
    kubernetes.io/service-account.uid: 165f1407-5be0-4fea-8ac3-253f2aa034d8
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
