metadata:
  name: cattle-impersonation-u-p7vaiakhge-token-fxww6
  namespace: cattle-impersonation-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: cattle-impersonation-u-p7vaiakhge
    kubernetes.io/service-account.uid: 5da0b4df-d3f9-4d06-b8b8-a73e10754747
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
