metadata:
  name: cattle-impersonation-u-b4qkhsnliz-token-t7bns
  namespace: cattle-impersonation-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: cattle-impersonation-u-b4qkhsnliz
    kubernetes.io/service-account.uid: 1812a443-fd85-4a4f-b037-4f59589e9890
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
