metadata:
  name: cattle-impersonation-u-72uggsypy6
  namespace: cattle-impersonation-system
  labels:
    authz.cluster.cattle.io/impersonator: <REDACTED:env>
    cattle.io/creator: norman
secrets:
- name: cattle-impersonation-u-72uggsypy6-token-xvt6x
apiVersion: v1
kind: ServiceAccount
