metadata:
  name: cattle-impersonation-u-p7vaiakhge
  namespace: cattle-impersonation-system
  labels:
    authz.cluster.cattle.io/impersonator: <REDACTED:env>
    cattle.io/creator: norman
secrets:
- name: cattle-impersonation-u-p7vaiakhge-token-fxww6
apiVersion: v1
kind: ServiceAccount
