metadata:
  name: cattle-impersonation-u-mo773yttt4
  namespace: cattle-impersonation-system
  labels:
    authz.cluster.cattle.io/impersonator: <REDACTED:env>
    cattle.io/creator: norman
secrets:
- name: cattle-impersonation-u-mo773yttt4-token-d9l9n
apiVersion: v1
kind: ServiceAccount
