metadata:
  name: cattle-impersonation-u-opuz4wfoda
  namespace: cattle-impersonation-system
  labels:
    authz.cluster.cattle.io/impersonator: <REDACTED:env>
    cattle.io/creator: norman
secrets:
- name: cattle-impersonation-u-opuz4wfoda-token-zllvg
apiVersion: v1
kind: ServiceAccount
