metadata:
  name: crt-local-cluster-admin
  namespace: fleet-local
  labels:
    objectset.rio.cattle.io/hash: 681219f11986442341da5c4fc12c7e769fe6d0c3
  annotations:
    cluster.cattle.io/name: local
    cluster.cattle.io/namespace: fleet-local
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xRO4/UMBD+K2hKFC+XbN4SFQUFEsUJ0aAUE3u8a86xI9sJxSr/HTmXQIS07HV+fPPN97jBQAEFBoT2BmiMDRiUNT5euZ58IHfiGIKmk7IfDA4ELWjLUUNyB+BH5BElNVFgO9b2P4kHT+HklD1MKAEt4BSubHR2ZnPGnNUUaBg1Bno4bn8Zcuwyv0ALAxq80EAmHADzOXn3RRnx8dlq+rbRPiTcjG4GGYpBmTcN7eZhSUBjT3pN8t7cFf0VWijrNEsbmaZNXeZ5ds5TgQXPJU8zXlFVNpJK8cTPkXRX5rZo2b8a/1NBVPlMkhwZTh7aHzfAUX0n55U10EJsQMWzMpdjhCkk8KJMbOrT6zb4I2Qnn9YiRZU1siDJqkoKlmORMyzKJyZrkQlZn2sSPSzdkoCb9F8Jn52dxni7IwG6BBx5OzlOX6O/CH3dfPhZX7c4fPyYyfXr43volm75HQAA//+dRBVg7QIAAA
    objectset.rio.cattle.io/id: auth-prov-v2-roletemplate-local
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_51>/v3, Kind=RoleTemplate
    objectset.rio.cattle.io/owner-name: cluster-admin
    objectset.rio.cattle.io/owner-namespace: ''
rules:
- verbs:
  - '*'
  apiGroups:
  - <DOMAIN_130>
  resources:
  - clusters
  resourceNames:
  - local
apiVersion: <DOMAIN_1>/v1
kind: Role
