metadata:
  name: crt-local-u-b4qkhsnliz-admin-oxyidght3v
  namespace: fleet-local
  labels:
    authz.cluster.cattle.io/crtb-owner: <REDACTED:env>
    objectset.rio.cattle.io/hash: c91799d7d33c6d54875d60e0de3aa002f5734fc1
  annotations:
    cluster.cattle.io/name: local
    cluster.cattle.io/namespace: fleet-local
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSQY+bMBSE/0r1zpiSkIQEqZf20ENvUXuqenjYD3AxNrUNbRPx31cGoo2U7Co5Is143nzDGVryKNAj5GdArY1HL4124ZOr3nmyMUfvFcXSfNTYEuSgDEcF0RsC1yEPqlIReXbRmuI3ce/Ix1aaK4cUkAP2vmadNQMb1oxbXzBrFBVSC6mrd8zmrybLqqGBHFrUWFFL2l8JhjT68E1q8enLfOrRKPpObafQ0+cHn19K96zY/Glqp5U8MRSt1A85LzRmDmMECgtSE9/Q+hTfQpwATC88G1ujqyEHflhlh4PIRJryndhu9tlW7BJKBKWISbIut1m6KfkqnLO043aZit0GMvPvvxRV7dMBZsO9iccIwmhHKqdunfxqTd9BDrZAHoeuxsrT9HfFzd7F0kAEjdRh/zAL3LllYbPAGCNw/dwc8p/PZvxwZF8zrlvC+Gt8CQAA//9o9mw+CQMAAA
    objectset.rio.cattle.io/id: auth-prov-v2-crtb-rolebinding
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_51>/v3, Kind=ClusterRoleTemplateBinding
    objectset.rio.cattle.io/owner-name: u-b4qkhsnliz-admin
    objectset.rio.cattle.io/owner-namespace: local
subjects:
- kind: User
  apiGroup: <DOMAIN_1>
  name: u-b4qkhsnliz
roleRef:
  apiGroup: <DOMAIN_1>
  kind: Role
  name: crt-local-cluster-owner
apiVersion: <DOMAIN_1>/v1
kind: RoleBinding
