metadata:
  name: auth-dmplt
  generateName: auth-
  namespace: fleet-local
  labels:
    fleet.cattle.io/managed: 'true'
data:
  password: <REDACTED:secret>
  username: <REDACTED:secret>
type: <DOMAIN_43>/basic-auth
apiVersion: v1
kind: Secret
