metadata:
  name: harbor-registry
  namespace: harbor
  labels:
    app: harbor
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: 2.15.1
    chart: harbor
    heritage: Helm
    release: harbor
  annotations:
    meta.helm.sh/release-name: harbor
    meta.helm.sh/release-namespace: harbor
data:
  config.yml: "version: 0.1\nlog:\n  level: info\n  fields:\n    service: registry\n\
    storage:\n  filesystem:\n    rootdirectory: /storage\n  cache:\n    layerinfo:\
    \ redis\n  maintenance:\n    uploadpurging:\n      enabled: true\n      age: 168h\n\
    \      interval: 24h\n      dryrun: false\n  delete:\n    enabled: true\n  redirect:\n\
    \    disable: false\nredis:\n  addr: harbor-redis:6379\n  db: 2\n  username: \"\
    \"\n  password: \"\"\n  readtimeout: 10s\n  writetimeout: 10s\n  dialtimeout:\
    \ 10s\n  enableTLS: false\n  pool:\n    maxidle: 100\n    maxactive: 500\n   \
    \ idletimeout: 60s\nhttp:\n  addr: :5000\n  relativeurls: false\n  # set via environment\
    \ variable\n  # secret: placeholder\n  debug:\n    addr: localhost:5001\nauth:\n\
    \  htpasswd:\n    realm: harbor-registry-basic-realm\n    path: /etc/registry/passwd\n\
    validation:\n  disabled: true\ncompatibility:\n  schema1:\n    enabled: true\n"
  ctl-config.yml: '---

    protocol: "http"

    port: 8080

    log_level: info

    registry_config: "/etc/registry/<DOMAIN_36>"


    '
apiVersion: v1
kind: ConfigMap
