metadata:
  name: harbor-core
  namespace: harbor
  labels:
    app: harbor
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: 2.15.1
    chart: harbor
    component: core
    heritage: Helm
    release: harbor
  annotations:
    meta.helm.sh/release-name: harbor
    meta.helm.sh/release-namespace: harbor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
      component: core
      release: harbor
  template:
    metadata:
      labels:
        app: harbor
        app.kubernetes.io/component: core
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: harbor
        app.kubernetes.io/part-of: harbor
        app.kubernetes.io/version: 2.15.1
        chart: harbor
        component: core
        heritage: Helm
        release: harbor
      annotations:
        checksum/configmap: ab9776eb41fa031fcb51307d39c41e18e526ce3b296f697e013495f9e873fc7a
        checksum/secret: <REDACTED:env>
        checksum/secret-jobservice: <REDACTED:env>
    spec:
      volumes:
      - name: config
        configMap:
          name: harbor-core
          items:
          - key: <DOMAIN_29>
            path: <DOMAIN_29>
          defaultMode: 420
      - name: secret-key
        secret:
          secretName: <REDACTED:env>
          items:
          - key: secretKey
            path: key
          defaultMode: 420
      - name: token-service-private-key
        secret:
          secretName: <REDACTED:env>
          defaultMode: 420
      - name: psc
        emptyDir: {}
      containers:
      - name: core
        image: docker.io/goharbor/harbor-core:v2.15.1
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: harbor-core
        - secretRef:
            name: harbor-core
        env:
        - name: CORE_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-core
              key: secret
        - name: JOBSERVICE_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-jobservice
              key: JOBSERVICE_SECRET
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /etc/core/<DOMAIN_29>
          subPath: <DOMAIN_29>
        - name: secret-key
          mountPath: /etc/core/key
          subPath: key
        - name: token-service-private-key
          mountPath: /etc/core/private_key.pem
          subPath: <DOMAIN_97>
        - name: psc
          mountPath: /etc/core/token
        livenessProbe:
          httpGet:
            path: /api/v2.0/ping
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /api/v2.0/ping
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /api/v2.0/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 360
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
