metadata:
  name: data-harbor-redis-0
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: redis
    heritage: Helm
    release: harbor
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_52>
    volume.kubernetes.io/storage-provisioner: <DOMAIN_52>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-e3ae8af8-9901-43be-b574-3ec5bcfb3430
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
