metadata:
  name: harbor-trivy
  namespace: harbor
  labels:
    app: harbor
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: 2.15.1
    chart: harbor
    heritage: Helm
    release: harbor
  annotations:
    meta.helm.sh/release-name: harbor
    meta.helm.sh/release-namespace: harbor
spec:
  ports:
  - name: http-trivy
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: harbor
    component: trivy
    release: harbor
  clusterIP: <IP_26>
  clusterIPs:
  - <IP_26>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
apiVersion: v1
kind: Service
