metadata:
  name: default-token-wst89
  namespace: p-67wv8
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 21a7d0b5-0a18-412e-a5ec-c8235ce29dae
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
