metadata:
  name: cluster-owner
  namespace: p-d874n
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - '*'
  apiGroups:
  - <DOMAIN_51>
  resources:
  - projectroletemplatebindings
- verbs:
  - '*'
  apiGroups:
  - ''
  resources:
  - secrets
apiVersion: <DOMAIN_1>/v1
kind: Role
