metadata:
  name: local-fleet-local-owner-cluster-owner
  namespace: p-d874n
  labels:
    cattle.io/creator: norman
    local_local-fleet-local-owner: crtb-in-project-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_1>
  name: u-mo773yttt4
roleRef:
  apiGroup: <DOMAIN_1>
  kind: Role
  name: cluster-owner
apiVersion: <DOMAIN_1>/v1
kind: RoleBinding
