metadata:
  name: crtb-z5l5s-cluster-owner
  namespace: c-6tfcq
  labels:
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-ulqmnp7jyh
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: cluster-owner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
