metadata:
  name: cluster-owner
  namespace: c-6tfcq
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - nodepools
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projects
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - catalogtemplateversions
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clusteralertrules
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - notifiers
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - nodes
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clusterregistrationtokens
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clusterroletemplatebindings
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clusterscans
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clustermonitorgraphs
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clusteralertgroups
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clustercatalogs
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - etcdbackups
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - clusterloggings
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - catalogtemplates
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - podsecuritypolicytemplateprojectbindings
apiVersion: <DOMAIN_776>/v1
kind: Role
