metadata:
  name: default-token-lzkbx
  namespace: c-6tfcq
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 675e2a7b-82bf-487c-a84e-c8e6230f681e
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
