metadata:
  name: prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0
  namespace: cattle-prometheus
  labels:
    app: prometheus
    chart: prometheus-0.0.1
    monitoring.coreos.com: 'true'
    prometheus: cluster-monitoring
    release: cluster-monitoring
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_529>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: pvc-3485b66c-55d1-4d1b-aae8-81cca4990f92
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
