metadata:
  name: prometheus-cluster-monitoring
  namespace: cattle-prometheus
  labels:
    managed-by: prometheus-operator
    monitoring.coreos.com: 'true'
  annotations:
    generated: 'true'
data:
  prometheus.yaml.gz: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
