metadata:
  name: prometheus-cluster-monitoring-additional-alertmanager-configs
  namespace: cattle-prometheus
  labels:
    app: prometheus
    chart: prometheus-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
data:
  additional-alertmanager-configs.yaml: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
