metadata:
  name: prometheus-operator-monitoring-operator-token-rrcl2
  namespace: cattle-prometheus
  annotations:
    kubernetes.io/service-account.name: prometheus-operator-monitoring-operator
    kubernetes.io/service-account.uid: 78cb4d05-f41d-477e-aba3-04bfe6eb878b
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
