metadata:
  name: prometheus-cluster-monitoring-tls-assets
  namespace: cattle-prometheus
  labels:
    managed-by: prometheus-operator
    monitoring.coreos.com: 'true'
type: Opaque
apiVersion: v1
kind: Secret
