metadata:
  name: operator-init-cluster-monitoring-token-gmcnd
  namespace: cattle-prometheus
  annotations:
    kubernetes.io/service-account.name: operator-init-cluster-monitoring
    kubernetes.io/service-account.uid: e9eb04d8-2774-427f-9830-fca0c5a347f0
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
