metadata:
  name: cluster-monitoring-token-t7xxs
  namespace: cattle-prometheus
  annotations:
    kubernetes.io/service-account.name: cluster-monitoring
    kubernetes.io/service-account.uid: 7837d29a-9fa8-44e4-91d7-c0fbcbda03ae
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
