metadata:
  name: exporter-node-cluster-monitoring
  namespace: cattle-prometheus
  labels:
    app: exporter-node
    chart: exporter-node-0.0.1
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
secrets:
- name: exporter-node-cluster-monitoring-token-s4drh
apiVersion: v1
kind: ServiceAccount
