metadata:
  name: operator-init-cluster-monitoring
  namespace: cattle-prometheus
  labels:
    app: operator-init
    chart: operator-init-0.1.0
    heritage: Tiller
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
secrets:
- name: operator-init-cluster-monitoring-token-gmcnd
apiVersion: v1
kind: ServiceAccount
