metadata:
  name: prometheus-operator-monitoring-operator
  namespace: cattle-prometheus
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.2
    heritage: Tiller
    io.cattle.field/appId: monitoring-operator
    release: monitoring-operator
secrets:
- name: prometheus-operator-monitoring-operator-token-rrcl2
apiVersion: v1
kind: ServiceAccount
