metadata:
  name: default-token-mqtls
  namespace: kube-public
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: ced0c34c-d2c2-4cd7-b5a4-19bd2c05b3e7
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
