metadata:
  name: capi-env-variables
  namespace: cattle-capi-system
data:
  CLUSTER_TOPOLOGY: <REDACTED:secret>
  EXP_CLUSTER_RESOURCE_SET: <REDACTED:secret>
  EXP_MACHINE_POOL: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
