metadata:
  name: logstash-configmap
  namespace: elk
  annotations: {}
data:
  logstash.conf: "# all input will come from filebeat, no local logs\ninput {\n  beats\
    \ {\n    port => 5044\n  }\n}\nfilter {\n}\noutput {\n  if [fields][log_type]\
    \ == \"fem-logs\" {\n    elasticsearch {\n      hosts => \"${ES_HOSTS}\"\n   \
    \   index => \"fem-%{+<DOMAIN_469>}\"\n      user => \"${ES_USER}\"\n      password\
    \ => \"${ES_PASSWORD}\"\n      ssl_certificate_verification => false\n    }\n\
    \  }\n  if [fields][log_type] == \"okr-logs\" {\n    elasticsearch {\n      hosts\
    \ => \"${ES_HOSTS}\"\n      index => \"okr-%{+<DOMAIN_469>}\"\n      user => \"\
    ${ES_USER}\"\n      password => \"${ES_PASSWORD}\"\n      ssl_certificate_verification\
    \ => false\n    }\n  }\n  if [fields][log_type] == \"echecklist-logs\" {\n   \
    \ elasticsearch {\n      hosts => \"${ES_HOSTS}\"\n      index => \"echecklist-%{+<DOMAIN_469>}\"\
    \n      user => \"${ES_USER}\"\n      password => \"${ES_PASSWORD}\"\n      ssl_certificate_verification\
    \ => false\n    }\n  }\n  if [fields][log_type] == \"acs-logs\" {\n    elasticsearch\
    \ {\n      hosts => \"${ES_HOSTS}\"\n      index => \"acs-%{+<DOMAIN_469>}\"\n\
    \      user => \"${ES_USER}\"\n      password => \"${ES_PASSWORD}\"\n      ssl_certificate_verification\
    \ => false\n    }\n  }\n}\n"
  logstash.yml: '<DOMAIN_470>: "0.0.0.0"

    <DOMAIN_471>: /usr/share/logstash/pipeline

    '
apiVersion: v1
kind: ConfigMap
