metadata:
  name: default-token-ckhjk
  namespace: elk
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 6d5f1f64-e113-4c9d-9558-f3a64c485a73
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
