metadata:
  name: logstash-service
  namespace: elk
  labels:
    app: logstash
  annotations: {}
spec:
  ports:
  - name: '25826'
    protocol: TCP
    port: 25826
    targetPort: 25826
  - name: '5044'
    protocol: TCP
    port: 5044
    targetPort: 5044
  - name: '9600'
    protocol: TCP
    port: 9600
    targetPort: 9600
  selector:
    app: logstash
  clusterIP: <IP_61>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
