metadata:
  name: local
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2020-10-07T04:13:58Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2020-10-07T04:13:58Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    management.cattle.io/system-namespace: 'true'
spec: {}
apiVersion: v1
kind: Namespace
