metadata:
  name: cattle-fleet-system
  labels:
    field.cattle.io/projectId: p-wnc8s
    objectset.rio.cattle.io/hash: 4510303f19b6cbafc9031148b1866f16c2be7aaa
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-07-28T08:26:22Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2022-07-28T08:26:27Z"}]}'
    field.cattle.io/projectId: local:p-wnc8s
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3zOS26EMAyA4bt4DZQUmkLO0Qs4wRGp8kDYLEaIu48C+9nZsvT9PiGR4IKCYE7AnIughJK5rsX+kxMm6fZQOocikbpQvsICBnwkktaWIiw7bu1tXA24nW7hLyRiwbSByUeMDUS0FD+6K/IKBsYf1Q/94NVstbPo3dwPSo2TVZPWXmn3bekX8a5lTAQGHqN9fuIXC6V65Y0cmLNOgnLU+HW9AwAA///+sh4F8wAAAA
    objectset.rio.cattle.io/id: fleet-bootstrap-data
spec: {}
apiVersion: v1
kind: Namespace
