metadata:
  name: fleet-local
  labels:
    field.cattle.io/projectId: p-wnc8s
    objectset.rio.cattle.io/hash: 67f475f626e5473772f6084a291170a9de5942d1
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2020-10-07T07:39:11Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2020-10-07T07:39:11Z"}]}'
    field.cattle.io/projectId: local:p-wnc8s
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOQW7FIAxE7+L1b/pDCTScoxdwwOhTGRwFZxXl7hVddNndzEgzby6opJhQEcIF2JooapHWh5Xtm6J20ukoMkVUZZqKvJcEATIT6dsmol0P3OF+QDzot/xVKnXFukNoJ/MDGDfifydf2F8QwPls/ZKdcbRY/+G9ye75adGs8+yfuCZaVmvSPGgNK/39YInII+07RQjXUIp6Duh9/wQAAP//ZXflOeYAAAA
    objectset.rio.cattle.io/id: fleet-bootstrap
spec: {}
apiVersion: v1
kind: Namespace
