metadata:
  name: argocd
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2021-04-13T10:16:00Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2021-04-13T10:16:00Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
