metadata:
  name: face-reco
  labels:
    field.cattle.io/projectId: p-67wv8
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-04-08T07:02:56Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2022-04-08T07:02:56Z"}]}'
    field.cattle.io/projectId: local:p-67wv8
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
