metadata:
  name: cattle-logging
  labels:
    cattle.io/creator: norman
    field.cattle.io/projectId: p-wnc8s
  annotations:
    cattle.io/appIds: rancher-logging
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2020-10-07T08:20:50Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2020-10-07T08:20:55Z"}]}'
    field.cattle.io/projectId: local:p-wnc8s
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
