metadata:
  name: moodle-v2
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2023-07-31T04:00:26Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2023-07-31T04:00:26Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
