metadata:
  name: fleet-default
  labels:
    field.cattle.io/projectId: p-wnc8s
    objectset.rio.cattle.io/hash: 7e7ea272a8ed59a1ca6ea1587cb55d693b393102
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2020-10-07T07:34:16Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2020-10-07T07:34:16Z"}]}'
    field.cattle.io/projectId: local:p-wnc8s
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQvU7DQBCEXwVtfTHYluP4JFoaWiTq9d0kOXI/lm+dFJbfHR00FIDS7Uoz8+3OSgHCloVJr8QxJmFxKeaypvEDRjKkml2qDIt4VC49Okuabmm+5IkNSP0pTLeIeXe6XkhT4MgnBET5Ibi26uHVRfv84gF5vzsycgBpOhbXzuLIi5e7TN/xmmhTZGZ8/frmArJwmEjHxXtFnkf4fxs4cz6Tph49uOkbPsB2A9eG9+C6O/Rm7Dq7H9qxHdr6qSm0X0/eFOUJhvRaJmFZCnbbPgMAAP//qGc0XpcBAAA
    objectset.rio.cattle.io/id: workspace
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=FleetWorkspace
    objectset.rio.cattle.io/owner-name: fleet-default
    objectset.rio.cattle.io/owner-namespace: ''
spec: {}
apiVersion: v1
kind: Namespace
