metadata:
  name: p-67wv8
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-04-13T02:46:03Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2022-04-13T02:46:03Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    management.cattle.io/system-namespace: 'true'
spec: {}
apiVersion: v1
kind: Namespace
