metadata:
  name: u-pdq5vm372s
  labels:
    cattle.io/creator: norman
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2022-07-01T09:41:12Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2022-07-01T09:41:12Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    management.cattle.io/system-namespace: 'true'
spec: {}
apiVersion: v1
kind: Namespace
