metadata:
  name: moodle
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2021-01-07T02:50:26Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2021-01-07T02:50:26Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
