metadata:
  name: u-67ijcr2wgu
  labels:
    cattle.io/creator: norman
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2024-11-07T02:23:48Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2024-11-07T02:23:48Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/system-namespace: 'true'
spec: {}
apiVersion: v1
kind: Namespace
