metadata:
  name: pvc-94a6b688-d201-43ca-93cb-3d860d533f6b
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_529>
spec:
  capacity:
    storage: 2Gi
  csi:
    driver: <DOMAIN_529>
    volumeHandle: 0001-0004-ceph-0000000000000002-bfe7fde0-1ec3-11ee-b728-b66af3768d5f
    fsType: ext4
    volumeAttributes:
      clusterID: ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-bfe7fde0-1ec3-11ee-b728-b66af3768d5f
      journalPool: ceph-replica-pool
      pool: ceph-replica-pool
      radosNamespace: ''
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_536>
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: passbolt-v4
    name: passbolt-pv-passbolt-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
