metadata:
  name: pvc-409bbe9d-ca95-4fca-b933-fba9b5f0dc95
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_529>
spec:
  capacity:
    storage: 2Gi
  csi:
    driver: <DOMAIN_529>
    volumeHandle: 0001-0004-ceph-0000000000000002-3408929e-53e5-11eb-a33a-e6be5504b8e7
    fsType: ext4
    volumeAttributes:
      clusterID: ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-3408929e-53e5-11eb-a33a-e6be5504b8e7
      journalPool: ceph-replica-pool
      pool: ceph-replica-pool
      radosNamespace: ''
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_533>
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: passbolt
    name: passbolt-pv-passbolt-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
