metadata:
  name: pvc-3a273a36-2dbe-4e55-829a-4883be9d1731
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_529>
spec:
  capacity:
    storage: 100Gi
  csi:
    driver: <DOMAIN_529>
    volumeHandle: 0001-0004-ceph-0000000000000002-ccfab979-2c84-11eb-9182-529d77288d93
    fsType: ext4
    volumeAttributes:
      clusterID: ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-ccfab979-2c84-11eb-9182-529d77288d93
      journalPool: ceph-replica-pool
      pool: ceph-replica-pool
      radosNamespace: ''
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_538>
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: kube-system
    name: elasticsearch-pvc-els-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
