metadata:
  name: pvc-4402dadd-2f95-4daa-96c9-51018f1aee5b
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_529>
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: <DOMAIN_529>
    volumeHandle: 0001-0004-ceph-0000000000000002-115c0b13-4ffd-11eb-a33a-e6be5504b8e7
    fsType: ext4
    volumeAttributes:
      clusterID: ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-115c0b13-4ffd-11eb-a33a-e6be5504b8e7
      journalPool: ceph-replica-pool
      pool: ceph-replica-pool
      radosNamespace: ''
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_533>
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: fem
    name: fem-prd-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
