metadata:
  name: default-token-dfl88
  namespace: u-7gfxvb5zzi
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: d563867f-1ec7-4bbe-ac14-b55fab647cd8
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
