metadata:
  name: be-env-vars-v001
  namespace: otm
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: otm
    moniker.spinnaker.io/sequence: <REDACTED:env>
  annotations:
    artifact.spinnaker.io/location: <REDACTED:env>
    artifact.spinnaker.io/name: <REDACTED:env>
    artifact.spinnaker.io/type: <REDACTED:env>
    artifact.spinnaker.io/version: <REDACTED:env>
    moniker.spinnaker.io/application: <REDACTED:env>
    moniker.spinnaker.io/cluster: <REDACTED:env>
    moniker.spinnaker.io/sequence: <REDACTED:env>
data:
  AUTH_URL: <REDACTED:env>
  DEBUG: 'True'
  ENV: PRD
  MAIL_PREFIX: PRD
  MAIL_SERVICE_ENDPOINT: <CLEANUP_IP_4>:9906
  SERVER: http://<CLEANUP_IP_5>:31088/
  samba_host: <CLEANUP_IP_6>
  samba_password: <REDACTED:env>
  samba_share: Public
  samba_user: ''
apiVersion: v1
kind: ConfigMap
