metadata:
  name: default-token-8w5xv
  namespace: otm
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: f131338a-f299-4421-ae0b-9a0f2a6d3eea
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
