metadata:
  name: otm-prd-be-secret
  namespace: otm
data:
  AES_KEY: <REDACTED:secret>
  ENCRYPT_KEY: <REDACTED:secret>
  db_host: <REDACTED:secret>
  db_name: <REDACTED:secret>
  db_password: <REDACTED:secret>
  db_port: <REDACTED:secret>
  db_user: <REDACTED:secret>
  email_service_auth_token: <REDACTED:secret>
  email_service_password: <REDACTED:secret>
  email_service_user: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
