metadata:
  name: default-token-9wndm
  namespace: u-75yktoly4h
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: dc616a2a-a69b-4976-ac65-8be8bb02d71a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
