metadata:
  name: p-j78jh-projectowner
  namespace: local
rules:
- verbs:
  - get
  - update
  - delete
  - patch
  - create
  - list
  - watch
  - deletecollection
  apiGroups:
  - <DOMAIN_51>
  resources:
  - projects
  resourceNames:
  - p-j78jh
apiVersion: <DOMAIN_1>/v1
kind: Role
