metadata:
  name: u-b4qkhsnliz-admin-cluster-owner
  namespace: local
  labels:
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_1>
  name: u-b4qkhsnliz
roleRef:
  apiGroup: <DOMAIN_1>
  kind: Role
  name: cluster-owner
apiVersion: <DOMAIN_1>/v1
kind: RoleBinding
