metadata:
  name: p-j78jh-projectmember
  namespace: local
rules:
- verbs:
  - get
  apiGroups:
  - <DOMAIN_51>
  resources:
  - projects
  resourceNames:
  - p-j78jh
apiVersion: <DOMAIN_1>/v1
kind: Role
