metadata:
  name: default-token-4ld55
  namespace: kube-node-lease
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: a6b6e0fb-3f91-45e8-a532-80d76987b2a4
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
