metadata:
  name: grb-nkp5b-global-catalog-binding
  namespace: cattle-global-data
  labels:
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-ymbjie6od7
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: admin-global-catalog
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
