metadata:
  name: grb-m6z9b-global-catalog-binding
  namespace: cattle-global-data
  labels:
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-zoriiln52e
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: user-global-catalog
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
