metadata:
  name: regcred-bart
  namespace: fem
  labels:
    app.kubernetes.io/instance: fem-prd
  annotations: {}
data:
  .dockerconfigjson: <REDACTED:secret>
type: <DOMAIN_138>/dockerconfigjson
apiVersion: v1
kind: Secret
