metadata:
  name: default-token-5mjb7
  namespace: opn
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 1efe1cf3-cdf1-4cad-b371-0db8f262179a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
