metadata:
  name: default-token-6pmkm
  namespace: u-fzbdx
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 03f77065-a15d-4150-a1d4-c6cdaef7d5f0
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
