metadata:
  name: default-token-2b2lk
  namespace: p-v75v8
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: e9611997-bb0f-482b-9327-dda5a8468b3c
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
