metadata:
  name: rook-ceph-exporter-<CLEANUP_HOST_2>
  namespace: rook-ceph
  labels:
    app: rook-ceph-exporter
    ceph-version: 19.2.3-0
    ceph_daemon_id: exporter
    kubernetes.io/hostname: <CLEANUP_HOST_2>
    node_name: <CLEANUP_HOST_2>
    rook-version: v1.19.2
    rook_cluster: rook-ceph
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-exporter
      kubernetes.io/hostname: <CLEANUP_HOST_2>
      node_name: <CLEANUP_HOST_2>
  template:
    metadata:
      labels:
        app: rook-ceph-exporter
        ceph-version: 19.2.3-0
        ceph_daemon_id: exporter
        kubernetes.io/hostname: <CLEANUP_HOST_2>
        node_name: <CLEANUP_HOST_2>
        rook-version: v1.19.2
        rook_cluster: rook-ceph
      annotations:
        prometheus.io/port: '9926'
        prometheus.io/scrape: 'true'
    spec:
      volumes:
      - name: rook-config-override
        projected:
          sources:
          - configMap:
              name: rook-config-override
              items:
              - key: config
                path: <DOMAIN_100>
                mode: 292
          defaultMode: 420
      - name: ceph-daemons-sock-dir
        hostPath:
          path: /var/lib/rook/exporter
          type: DirectoryOrCreate
      - name: rook-ceph-log
        hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ''
      - name: rook-ceph-crash
        hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ''
      - name: rook-ceph-exporter-keyring
        secret:
          secretName: <REDACTED:env>
          defaultMode: 420
      initContainers:
      - name: chown-container-data-dir
        image: quay.io/ceph/ceph:v19.2.3
        command:
        - chown
        args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /run/ceph
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: ceph-daemons-sock-dir
          mountPath: /run/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: false
      containers:
      - name: ceph-exporter
        image: quay.io/ceph/ceph:v19.2.3
        command:
        - ceph-exporter
        args:
        - --sock-dir
        - /run/ceph
        - --port
        - '9926'
        - --prio-limit
        - '5'
        - --stats-period
        - '5'
        ports:
        - name: http-metrics
          containerPort: 9926
          protocol: TCP
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v19.2.3
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_24>
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_72>
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_66>
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_101>
              divisor: '0'
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_102>
              divisor: '0'
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_103>
              divisor: '1'
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: <DOMAIN_104>
              divisor: '0'
        - name: CEPH_USE_RANDOM_NONCE
          value: 'true'
        - name: ROOK_MSGR2
          value: msgr2_false_encryption_false_compression_false
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_host
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              name: rook-ceph-config
              key: mon_initial_members
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST) -n <DOMAIN_106>-exporter -k /etc/ceph/exporter-keyring-store/keyring
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: ceph-daemons-sock-dir
          mountPath: /run/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: rook-ceph-exporter-keyring
          readOnly: true
          mountPath: /etc/ceph/exporter-keyring-store/
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: false
      - name: log-collector
        image: quay.io/ceph/ceph:v19.2.3
        command:
        - /bin/bash
        - -x
        - -e
        - -m
        - -c
        - "\nCEPH_CLIENT_ID=<DOMAIN_107>-exporter\nPERIODICITY=daily\nLOG_ROTATE_CEPH_FILE=/etc/logrotate.d/ceph\n\
          LOG_MAX_SIZE=500M\nROTATE=7\nADDITIONAL_LOG_FILES=\n\n# edit the logrotate\
          \ file to only rotate a specific daemon log\n# otherwise we will logrotate\
          \ log files without reloading certain daemons\n# this might happen when\
          \ multiple daemons run on the same machine\nsed -i \"s|*.log|$CEPH_CLIENT_ID.log\
          \ $ADDITIONAL_LOG_FILES|\" \"$LOG_ROTATE_CEPH_FILE\"\n\n# replace default\
          \ daily with given user input\nsed --in-place \"s/daily/$PERIODICITY/g\"\
          \ \"$LOG_ROTATE_CEPH_FILE\"\n\n# replace rotate count, default 7 for all\
          \ ceph daemons other than rbd-mirror\nsed --in-place \"s/rotate 7/rotate\
          \ $ROTATE/g\" \"$LOG_ROTATE_CEPH_FILE\"\n\nif [ \"$LOG_MAX_SIZE\" != \"\
          0\" ]; then\n\t# adding maxsize $LOG_MAX_SIZE at the 4th line of the logrotate\
          \ config file with 4 spaces to maintain indentation\n\tsed --in-place \"\
          4i \\ \\ \\ \\ maxsize $LOG_MAX_SIZE\" \"$LOG_ROTATE_CEPH_FILE\"\nfi\n\n\
          while true; do\n\t# we don't force the logrorate but we let the logrotate\
          \ binary handle the rotation based on user's input for periodicity and size\n\
          \tlogrotate --verbose \"$LOG_ROTATE_CEPH_FILE\"\n\tsleep 15m\ndone\n"
        resources: {}
        volumeMounts:
        - name: rook-config-override
          readOnly: true
          mountPath: /etc/ceph
        - name: ceph-daemons-sock-dir
          mountPath: /run/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: false
        tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 2
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: <CLEANUP_HOST_2>
      serviceAccountName: rook-ceph-default
      serviceAccount: rook-ceph-default
      shareProcessNamespace: true
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
      - key: <DOMAIN_105>/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: <DOMAIN_105>/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
