metadata:
  name: rook-ceph-osd-prepare-ceph-osd-set-data-1hvqrb
  namespace: rook-ceph
  labels:
    app: rook-ceph-osd-prepare
    ceph-version: 19.2.3-0
    ceph.rook.io/DeviceSet: ceph-osd-set
    ceph.rook.io/pvc: ceph-osd-set-data-1hvqrb
    rook-version: v1.19.2
    rook_cluster: rook-ceph
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 7a9632ac-d0dd-488d-9648-67d0abbe53f4
  manualSelector: false
  template:
    metadata:
      name: rook-ceph-osd
      labels:
        app: rook-ceph-osd-prepare
        batch.kubernetes.io/controller-uid: 7a9632ac-d0dd-488d-9648-67d0abbe53f4
        batch.kubernetes.io/job-name: rook-ceph-osd-prepare-ceph-osd-set-data-1hvqrb
        ceph.rook.io/DeviceSet: ceph-osd-set
        ceph.rook.io/pvc: ceph-osd-set-data-1hvqrb
        controller-uid: 7a9632ac-d0dd-488d-9648-67d0abbe53f4
        device-class: ''
        job-name: rook-ceph-osd-prepare-ceph-osd-set-data-1hvqrb
        rook_cluster: rook-ceph
    spec:
      volumes:
      - name: rook-data
        hostPath:
          path: /var/lib/rook
          type: ''
      - name: ceph-conf-emptydir
        emptyDir: {}
      - name: ceph-daemons-sock-dir
        hostPath:
          path: /var/lib/rook/exporter
          type: DirectoryOrCreate
      - name: rook-ceph-log
        hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ''
      - name: rook-ceph-crash
        hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ''
      - name: rook-binaries
        emptyDir: {}
      - name: udev
        hostPath:
          path: /run/udev
          type: ''
      - name: devices
        hostPath:
          path: /dev
          type: ''
      - name: ceph-admin-secret
        secret:
          secretName: <REDACTED:env>
          items:
          - key: ceph-secret
            path: <DOMAIN_108>
          defaultMode: 420
      - name: ceph-osd-set-data-1hvqrb
        persistentVolumeClaim:
          claimName: ceph-osd-set-data-1hvqrb
      - name: ceph-osd-set-data-1hvqrb-bridge
        emptyDir:
          medium: Memory
      initContainers:
      - name: copy-bins
        image: docker.io/rook/ceph:v1.19.2
        command:
        - cp
        args:
        - --archive
        - --force
        - --verbose
        - /usr/local/bin/rook
        - /rook
        resources: {}
        volumeMounts:
        - name: rook-binaries
          mountPath: /rook
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: blkdevmapper
        image: quay.io/ceph/ceph:v19.2.3
        command:
        - /bin/bash
        - -c
        - "\nset -xe\n\nPVC_SOURCE=/ceph-osd-set-data-1hvqrb\nPVC_DEST=/mnt/ceph-osd-set-data-1hvqrb\n\
          CP_ARGS=(--archive --dereference --verbose)\n\nif [ -b \"$PVC_DEST\" ];\
          \ then\n\tPVC_SOURCE_MAJ_MIN=$(stat --format '%t%T' $PVC_SOURCE)\n\tPVC_DEST_MAJ_MIN=$(stat\
          \ --format '%t%T' $PVC_DEST)\n\tif [[ \"$PVC_SOURCE_MAJ_MIN\" == \"$PVC_DEST_MAJ_MIN\"\
          \ ]]; then\n\t\techo \"PVC $PVC_DEST already exists and has the same major\
          \ and minor as $PVC_SOURCE: \"$PVC_SOURCE_MAJ_MIN\"\"\n\t\texit 0\n\telse\n\
          \t\techo \"PVC's source major/minor numbers changed\"\n\t\tCP_ARGS+=(--remove-destination)\n\
          \tfi\nfi\n\ncp \"${CP_ARGS[@]}\" \"$PVC_SOURCE\" \"$PVC_DEST\"\n"
        resources: {}
        volumeMounts:
        - name: ceph-osd-set-data-1hvqrb-bridge
          mountPath: /mnt
        volumeDevices:
        - name: ceph-osd-set-data-1hvqrb
          devicePath: /ceph-osd-set-data-1hvqrb
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - MKNOD
            drop:
            - NET_RAW
          privileged: false
      containers:
      - name: provision
        image: quay.io/ceph/ceph:v19.2.3
        command:
        - /rook/rook
        args:
        - ceph
        - osd
        - provision
        envFrom:
        - configMapRef:
            name: rook-ceph-osd-env-override
            optional: true
        env:
        - name: ROOK_NODE_NAME
          value: ceph-osd-set-data-1hvqrb
        - name: ROOK_CLUSTER_ID
          value: 6ef43355-6835-4968-90b8-cc50af05aa2c
        - name: ROOK_CLUSTER_NAME
          value: rook-ceph
        - name: ROOK_PRIVATE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_71>
        - name: ROOK_PUBLIC_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_71>
        - name: POD_NAMESPACE
          value: rook-ceph
        - name: ROOK_MON_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: rook-ceph-mon-endpoints
              key: data
        - name: ROOK_CONFIG_DIR
          value: /var/lib/rook
        - name: ROOK_CEPH_CONFIG_OVERRIDE
          value: /etc/rook/config/<DOMAIN_110>
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: <DOMAIN_66>
        - name: ROOK_CRUSHMAP_ROOT
          value: default
        - name: ROOK_CEPH_USERNAME
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: ceph-username
        - name: ROOK_FSID
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: fsid
        - name: ROOK_OSD_STORE_TYPE
          value: bluestore
        - name: ROOK_CRUSHMAP_HOSTNAME
        - name: CEPH_VOLUME_DEBUG
          value: '1'
        - name: CEPH_VOLUME_SKIP_RESTORECON
          value: '1'
        - name: DM_DISABLE_UDEV
          value: '1'
        - name: ROOK_LOG_LEVEL
          value: DEBUG
        - name: ROOK_CEPH_VERSION
          value: ceph version 19.2.3-0 squid
        - name: ROOK_OSD_CRUSH_DEVICE_CLASS
        - name: ROOK_OSD_CRUSH_INITIAL_WEIGHT
        - name: CEPH_VOLUME_ALLOW_LOOP_DEVICES
          value: 'true'
        - name: ROOK_DATA_DEVICES
          value: '[{"id":"/mnt/ceph-osd-set-data-1hvqrb","storeConfig":{"osdsPerDevice":1}}]'
        - name: ROOK_PVC_BACKED_OSD
          value: 'true'
        - name: ROOK_ENCRYPTED_DEVICE
          value: 'false'
        - name: ROOK_PVC_NAME
          value: ceph-osd-set-data-1hvqrb
        resources: {}
        volumeMounts:
        - name: rook-data
          mountPath: /var/lib/rook
        - name: ceph-conf-emptydir
          mountPath: /etc/ceph
        - name: ceph-daemons-sock-dir
          mountPath: /run/ceph
        - name: rook-ceph-log
          mountPath: /var/log/ceph
        - name: rook-ceph-crash
          mountPath: /var/lib/ceph/crash
        - name: devices
          mountPath: /dev
        - name: udev
          mountPath: /run/udev
        - name: rook-binaries
          mountPath: /rook
        - name: ceph-admin-secret
          readOnly: true
          mountPath: /var/lib/rook-ceph-mon
        - name: ceph-osd-set-data-1hvqrb-bridge
          mountPath: /mnt
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: true
          runAsUser: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: false
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: rook-ceph-osd
      serviceAccount: rook-ceph-osd
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
      priorityClassName: system-node-critical
  completionMode: NonIndexed
  suspend: false
  podReplacementPolicy: TerminatingOrFailed
apiVersion: batch/v1
kind: Job
