metadata:
  name: rbd-csi-nodeplugin-role-cfg
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    operator: rook
    storage-backend: ceph
subjects:
- kind: ServiceAccount
  name: rook-csi-rbd-plugin-sa
  namespace: rook-ceph
roleRef:
  apiGroup: <DOMAIN_1>
  kind: Role
  name: rbd-csi-nodeplugin
apiVersion: <DOMAIN_1>/v1
kind: RoleBinding
