metadata:
  name: ceph-csi-leader-election-role
  namespace: rook-ceph
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ceph-csi-operator
rules:
- verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  apiGroups:
  - ''
  resources:
  - configmaps
- verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  apiGroups:
  - <DOMAIN_129>
  resources:
  - leases
- verbs:
  - create
  - patch
  apiGroups:
  - ''
  resources:
  - events
apiVersion: <DOMAIN_1>/v1
kind: Role
