metadata:
  name: objectstorage-provisioner
  namespace: rook-ceph
  labels:
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
    app.kubernetes.io/part-of: container-object-storage-interface
apiVersion: v1
kind: ServiceAccount
