metadata:
  name: clusterrolebinding-9x5hb
  generateName: clusterrolebinding-
  namespace: passbolt-v4
  labels:
    authz.cluster.cattle.io/rtb-owner-updated: <REDACTED:env>
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-v4ccd
roleRef:
  apiGroup: <DOMAIN_776>
  kind: ClusterRole
  name: admin
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
