metadata:
  name: passbolt-key-fingerprint
  namespace: passbolt-v4
  labels:
    app.kubernetes.io/instance: passbolt-v4
  annotations: {}
data:
  fingerprint: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
