metadata:
  name: mysql-root-password
  namespace: passbolt-v4
  labels:
    app.kubernetes.io/instance: passbolt-v4
  annotations: {}
data:
  password: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
