metadata:
  name: cattle-impersonation-u-mo773yttt4-token-bnb8m
  generateName: cattle-impersonation-u-mo773yttt4-token-
  namespace: cattle-impersonation-system
  labels:
    cattle.io/service-account.name: cattle-impersonation-u-mo773yttt4
  annotations:
    field.cattle.io/projectId: local:p-j78jh
    kubernetes.io/service-account.name: cattle-impersonation-u-mo773yttt4
    kubernetes.io/service-account.uid: 2533792f-0867-45c8-952f-6df10027b599
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_43>/service-account-token
apiVersion: v1
kind: Secret
