metadata:
  name: cattle-impersonation-u-b4qkhsnliz-token-cf7rg
  generateName: cattle-impersonation-u-b4qkhsnliz-token-
  namespace: cattle-impersonation-system
  labels:
    cattle.io/service-account.name: cattle-impersonation-u-b4qkhsnliz
  annotations:
    kubernetes.io/service-account.name: cattle-impersonation-u-b4qkhsnliz
    kubernetes.io/service-account.uid: 03dc7076-5426-49e0-9f59-8fc5bfc509d3
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_43>/service-account-token
apiVersion: v1
kind: Secret
