metadata:
  name: cattle-impersonation-u-mo773yttt4
  namespace: cattle-impersonation-system
  labels:
    authz.cluster.cattle.io/impersonator: <REDACTED:env>
  annotations:
    rancher.io/service-account.secret-ref: <REDACTED:env>
apiVersion: v1
kind: ServiceAccount
