metadata:
  name: default-token-7xg4b
  namespace: u-fxdujzgdcg
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 7646c546-18aa-4e6d-90bf-26a8bb74d40a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
