metadata:
  name: default-token-zwqc4
  namespace: u-h6bzv6cz5c
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 991f10f5-f6dc-4a37-a2e1-c36eb2f95cc4
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
