metadata:
  name: cluster-owner
  namespace: p-c6t6q
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - pipelines
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - pipelinesettings
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projectalertgroups
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projectcatalogs
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projectroletemplatebindings
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - catalogtemplateversions
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - catalogtemplates
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - pipelineexecutions
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - sourcecodeproviderconfigs
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projectloggings
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projectmonitorgraphs
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - apprevisions
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - projectalertrules
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - secrets
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - apps
apiVersion: <DOMAIN_776>/v1
kind: Role
