metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
  annotations: {}
data:
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: 'true'
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: 'false'
  ROOK_CSI_ENABLE_CEPHFS: 'true'
  ROOK_CSI_ENABLE_GRPC_METRICS: 'true'
  ROOK_CSI_ENABLE_RBD: 'true'
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: 'true'
apiVersion: v1
kind: ConfigMap
