metadata:
  name: rook-csi-rbd-plugin-sa-token-vjz8f
  namespace: rook-ceph
  annotations:
    kubernetes.io/service-account.name: rook-csi-rbd-plugin-sa
    kubernetes.io/service-account.uid: 11a9ffed-4fd5-43ac-a158-ed8ab5a8ff17
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
