metadata:
  name: rook-ceph-system-token-bd65q
  namespace: rook-ceph
  annotations:
    kubernetes.io/service-account.name: rook-ceph-system
    kubernetes.io/service-account.uid: f748f0c5-3465-4bed-a05d-7c4096ffd08b
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
