metadata:
  name: default-token-gpsfp
  namespace: rook-ceph
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: ef1288ad-e215-4f5b-8947-5c2549a66fe9
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
