metadata:
  name: u-hybao3vlgk-member-edit
  namespace: p-t2pmj
  labels:
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-hybao3vlgk
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: edit
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
