metadata:
  name: cattle-credentials-a1d76e1
  namespace: cattle-system
  annotations: {}
data:
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
  url: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
