metadata:
  name: tls-rancher
  namespace: cattle-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
data:
  tls.crt: <REDACTED:secret>
  tls.key: <REDACTED:secret>
type: <DOMAIN_138>/tls
apiVersion: v1
kind: Secret
