metadata:
  name: rancher-token-r84zj
  namespace: cattle-system
  annotations:
    field.cattle.io/projectId: local:p-wnc8s
    kubernetes.io/service-account.name: rancher
    kubernetes.io/service-account.uid: b1f4cdaa-f7a8-4a72-a38f-4f6eb7ae344d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
