metadata:
  name: default-token-287dx
  namespace: u-flixo7vavq
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 4e72408f-697c-422f-8e16-60f81bbb35a0
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
