metadata:
  name: data-moodle-mariadb-0
  namespace: moodle
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/name: mariadb
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: <DOMAIN_529>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-737aa8ee-7878-4732-83d0-704ee24b488c
  storageClassName: ceph-block-replica-2
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolumeClaim
