metadata:
  name: moodle
  namespace: moodle
  labels:
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    helm.sh/chart: moodle-10.0.0
  annotations: {}
data:
  moodle-password: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
