metadata:
  name: moodle-mariadb-token-zsz9t
  namespace: moodle
  annotations:
    kubernetes.io/service-account.name: moodle-mariadb
    kubernetes.io/service-account.uid: a7598b84-850b-4f70-bfdb-1f06579b6f1a
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
