metadata:
  name: default-token-652n5
  namespace: moodle
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: ec88748e-34e2-42ee-bde3-1f94f18844a7
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
