metadata:
  name: default-token-8f54t
  namespace: u-szrv4
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 18384146-4862-4245-b0a0-31b18a9b8565
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
