metadata:
  name: default-token-w29zw
  namespace: user-9h9cp
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 6b622ad0-a2c2-4848-b03b-3ce00bab2ecd
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
