metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.2.1
  annotations: {}
rules:
- verbs:
  - get
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  - pods
  - secrets
  - endpoints
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - services
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_775>
  resources:
  - ingresses
- verbs:
  - update
  apiGroups:
  - <DOMAIN_775>
  resources:
  - ingresses/status
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_775>
  resources:
  - ingressclasses
- verbs:
  - get
  - update
  apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - ingress-controller-leader
- verbs:
  - create
  apiGroups:
  - ''
  resources:
  - configmaps
- verbs:
  - create
  - patch
  apiGroups:
  - ''
  resources:
  - events
apiVersion: <DOMAIN_776>/v1
kind: Role
