metadata:
  name: ingress-nginx-admission-token-5cs7n
  namespace: ingress-nginx
  annotations:
    kubernetes.io/service-account.name: ingress-nginx-admission
    kubernetes.io/service-account.uid: e29e7980-1f35-429e-b5b4-74337c51bdf6
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
