metadata:
  name: default-token-xwh6r
  namespace: u-l7q8v
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 1de62b1e-a0e9-4b7d-b97c-290e55834f27
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
