metadata:
  name: fleet-controller
  namespace: cattle-fleet-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: fleet
    meta.helm.sh/release-namespace: cattle-fleet-system
rules:
- verbs:
  - '*'
  apiGroups:
  - ''
  resources:
  - configmaps
apiVersion: <DOMAIN_776>/v1
kind: Role
