metadata:
  name: default-token-c47b2
  namespace: cattle-fleet-system
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 2dff9912-91ea-456e-8520-a815f86d87f2
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
