metadata:
  name: stv-aggregation
  namespace: cattle-fleet-system
  labels:
    objectset.rio.cattle.io/hash: 3953b7dc118c799e6caed8083cd9902dbb4b8f9d
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xRX2/aMBD/KtM9JywhFJJIfWih/1JoV0JYl2kPjn0JJo7NbAdKK777FLpKm7ROfTzd/e737wUYsQTiF6CkR7WFGKapZ6epP55nLFnw88l8mWRplicP3mU2P+48O679JM2SHanvJg/LbJ97l0GaJee5J8bggFU1SogBH28GNFhu7q9WnPjJ9TfBDF2Lx1t/83Mp2TDN5mYh8oRc+Dm9ypfZ80rMLi4b9uydggOtFhADuZ579Ho2nO7Dp9l48DSbnLWzBQ2m65vd3T7qz/bRuuiftPnXOw8ODjRoyZspIqWyxHIlTTeqYo3UGrQ9zVWPEmsF9rj6zFnHs+EG9ZZTBOfdS7WTqN1qW0MMDZGkwgal/eNgGzifbrlkp2dfbtIPvpOkQYih4tbdYbFSqv4QxGwI7XCdaarxaHPBGzSWNBuIZSuEA4IUKP5rfkXMCmIIopOgGDHq+yEdRREOKUEWemFAWRR5fVYUgyIsI9ax/RZs7NYlVaWxOnLD6+JN1iuDWwpE65q9sdh0tjr5cyxRo6RoIP7+0iW/RG26F++mCg4UQtH6vsNPUOCRMS6JMOgAVdJqJQRqiK1u0YGay67Uv1r4Z87tsfwyYv4oROqG5Yi6gwEyt2Bs4LIiHA39k7Ls+wQOPw6HXwEAAP//RwjBtjEDAAA
    objectset.rio.cattle.io/id: apiservice
    objectset.rio.cattle.io/owner-gvk: <DOMAIN_528>/v3, Kind=APIService
    objectset.rio.cattle.io/owner-name: git-webhook
    objectset.rio.cattle.io/owner-namespace: ''
data:
  ca.crt: <REDACTED:secret>
  token: <REDACTED:secret>
  url: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
