metadata:
  name: gitjob-token-tl2sz
  namespace: cattle-fleet-system
  annotations:
    kubernetes.io/service-account.name: gitjob
    kubernetes.io/service-account.uid: 4a36ef39-980b-4ea8-aab0-389ad8396fa7
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
