metadata:
  name: <DOMAIN_550>-crd.v2
  namespace: cattle-fleet-system
  labels:
    modifiedAt: '1658997141'
    name: fleet-crd
    owner: helm
    version: '2'
data:
  release: <REDACTED:secret>
type: <DOMAIN_152>/release.v1
apiVersion: v1
kind: Secret
