metadata:
  name: fleet-controller-token-bl9h5
  namespace: cattle-fleet-system
  annotations:
    kubernetes.io/service-account.name: fleet-controller
    kubernetes.io/service-account.uid: 3cbc5e33-563d-4d12-a4e6-c47bef069357
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
