metadata:
  name: fleet-agent
  namespace: cattle-fleet-local-system
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: 362023f752e7f1989d8b652e029bd2c658ae7c44
  annotations:
    meta.helm.sh/release-name: fleet-agent-local
    meta.helm.sh/release-namespace: cattle-fleet-local-system
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOPQ6DMAxG7+K5oTT8cxsnMSVViBH2UiHuXiGmLoz2+/T0dlhIMaAijDtgzqyokbOcJ7sPeRXSYotceFRNVER+xgAjTIlIDb4pq3HMKrrhaq6RuWBij8nIV5QWOB6Q0FG6Nc8oM4xQtba01dQ1lrrpNfRD6F3bWCrt4IL1bdMjdb6uT2nGhf5z4HrKiv4kN0nHLwAA//+nZcfN/wAAAA
    objectset.rio.cattle.io/id: fleet-agent-bootstrap-cattle-fleet-local-system
apiVersion: v1
kind: ServiceAccount
