metadata:
  name: default
  namespace: cattle-fleet-local-system
  labels:
    app.kubernetes.io/managed-by: Helm
    objectset.rio.cattle.io/hash: 362023f752e7f1989d8b652e029bd2c658ae7c44
  annotations:
    meta.helm.sh/release-name: fleet-agent-local
    meta.helm.sh/release-namespace: cattle-fleet-local-system
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOTW7rMAwG78J15JenxH/a9QztBSjpU6NWFgOLLlAEuXtheJ/lDInB9yDeVBbZqr5j/ckBbyHs9CHfqOQSl4YTLVCOrEzuQVyrKGuW2nYU/4WgDdqtWbrAqgVdln85kqNUADX8iarGi2jTle/meDLHsUjgYtpvUyz0PFFhj/KyfON2I0eXwZ7tJY29xZj+z9McJz/0Fmc7+2jD0E+MMVyve7TyAnIUkXgrSododw67fTHn+RcAAP//F9FSKSABAAA
    objectset.rio.cattle.io/id: fleet-agent-bootstrap-cattle-fleet-local-system
automountServiceAccountToken: false
apiVersion: v1
kind: ServiceAccount
