metadata:
  name: rancher-logging-log-aggregator-psp-rolebinding
  namespace: cattle-logging
  labels:
    app: log-aggregator
    chart: log-aggregator-0.0.2
    heritage: Tiller
    io.cattle.field/appId: rancher-logging
    release: rancher-logging
subjects:
- kind: ServiceAccount
  name: rancher-logging-log-aggregator
  namespace: cattle-logging
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: rancher-logging-log-aggregator-psp-role
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
