metadata:
  name: rancher-logging-fluentd-token-w47zr
  namespace: cattle-logging
  annotations:
    kubernetes.io/service-account.name: rancher-logging-fluentd
    kubernetes.io/service-account.uid: 8e5bf178-9bb3-4c20-92ea-effc30cf4f6d
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
