metadata:
  name: rancher-logging-fluentd-ssl
  namespace: cattle-logging
  labels:
    app: fluentd-ssl
    app.kubernetes.io/managed-by: Tiller
    chart: fluentd-0.0.2
    heritage: Tiller
    io.cattle.field/appId: rancher-logging
    kubernetes.io/cluster-service: 'true'
    release: rancher-logging
data:
  cluster_local_ca.pem: <REDACTED:secret>
  cluster_local_client-cert.pem: <REDACTED:secret>
  cluster_local_client-key.pem: <REDACTED:secret>
  project_local_p-t2pmj_ca.pem: <REDACTED:secret>
  project_local_p-t2pmj_client-cert.pem: <REDACTED:secret>
  project_local_p-t2pmj_client-key.pem: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
