metadata:
  name: rancher-logging-fluentd-entry
  namespace: cattle-logging
  labels:
    app: fluentd-entry
    app.kubernetes.io/managed-by: Tiller
    chart: fluentd-0.0.2
    heritage: Tiller
    io.cattle.field/appId: rancher-logging
    kubernetes.io/cluster-service: 'true'
    release: rancher-logging
data:
  fluent.conf: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
