metadata:
  name: cattle-webhook-tls
  namespace: cattle-system
  annotations:
    listener.cattle.io/cn-rancher-webhook.cattle-system.svc: <DOMAIN_57>
    listener.cattle.io/fingerprint: SHA1=58476BDE4907766ACDD9FE3091484D56A046A2F6
data:
  tls.crt: <REDACTED:secret>
  tls.key: <REDACTED:secret>
type: <DOMAIN_43>/tls
apiVersion: v1
kind: Secret
