metadata:
  name: tls-rancher-internal
  namespace: cattle-system
  annotations:
    listener.cattle.io/cn-10.100.36.11: <IP_10>
    listener.cattle.io/cn-192.168.13.95: <IP_7>
    listener.cattle.io/fingerprint: SHA1=1D27DB00303B1A91248BAB3AD2FA947013831E63
data:
  tls.crt: <REDACTED:secret>
  tls.key: <REDACTED:secret>
type: <DOMAIN_43>/tls
apiVersion: v1
kind: Secret
