metadata:
  name: rancher-token-xnx5b
  generateName: rancher-token-
  namespace: cattle-system
  labels:
    cattle.io/service-account.name: rancher
  annotations:
    field.cattle.io/projectId: local:p-j78jh
    kubernetes.io/service-account.name: rancher
    kubernetes.io/service-account.uid: 0e2f02c2-814c-4a39-a39b-8bf92d4100eb
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_43>/service-account-token
apiVersion: v1
kind: Secret
