metadata:
  name: rancher-webhook
  namespace: cattle-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: rancher-webhook
    meta.helm.sh/release-namespace: cattle-system
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9443
  selector:
    app: rancher-webhook
  clusterIP: <IP_17>
  clusterIPs:
  - <IP_17>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
apiVersion: v1
kind: Service
