metadata:
  name: rancher-webhook-sudo
  namespace: cattle-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    cattle.io/description: SA which can be impersonated to bypass rancher-webhook
      validation
    meta.helm.sh/release-name: rancher-webhook
    meta.helm.sh/release-namespace: cattle-system
apiVersion: v1
kind: ServiceAccount
