metadata:
  name: <DOMAIN_7>
  namespace: p-j78jh
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
data:
  ca.crt: '-----BEGIN CERTIFICATE-----

    MIIDBTCCAe2gAwIBAgIIKH9L8rjcSLYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE

    AxMKa3ViZXJuZXRlczAeFw0yNjA3MDkwOTA3MjVaFw0zNjA3MDYwOTEyMjVaMBUx

    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK

    AoIBAQDwcWM0N65SSwlGLkVg/UTW5bwwPDXZbHw2njfmddRoKOpU5Yp+LfilSQc5

    gZuZdx5+o2jMEXQxIBPg2O8dZBAUYNo2X+dgPb1pZbgTf1eXcwVMdSw+pfVKidsx

    3u8+E6+8tkqCqIsncaTv7/xmyQ6/fteCyzMWoopqxXNH3sjy+DGmwU9EVfSmuanA

    Op+N5EZbNPX+Zxm4fgzDIh4a1XlqBvh1smdyM3yv74zDjvhLSOUK+rwJlL09QNew

    ZfgXyB081gJHEozNJIEY0O6O0aGt9r9IZfUpBNAU6K3ZlC84w2i9azxz91XJ1qz9

    vsQPMqee5ybnA9F5XpcWVe+YB70LAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP

    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSSWc+jwmkdIQjheDh2aM8tu8x+9zAV

    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCUU9UZedBr

    8/woaw+Qkz2SdakT+cDTmDYQFtegF+vmSQc/kVpZH+ilPFtGrYurfzIVYgMaVZTT

    qbX74GtV8SWz6eziPhrBjAqREDEEhZ65VLY5CamFDY9jHqc5vJhu4MnAjuNfDBPu

    9rfQ6ghb4rKLHkjwBOem0Y84Sf+hIL00SFvbWcpdjNN0ShwcO9yGn5F+DLMTNaYL

    M/F4YEhkuWvhcHhVRqIzVj+rFNWTMhgMwmskq+s+XegYLdyGh0FtvogstJ72SR6C

    09zbIdDvatv0+2nBi3uO9mzs2qvLGTWn1aA2PDDqUlGZDwdS2/thBPZrpVjCw2Wz

    JdV2k3sPZtdC

    -----END CERTIFICATE-----

    '
apiVersion: v1
kind: ConfigMap
