metadata:
  name: cattle-fleet-clusters-system
  labels:
    field.cattle.io/projectId: p-j78jh
    kubernetes.io/metadata.name: cattle-fleet-clusters-system
    objectset.rio.cattle.io/hash: 4510303f19b6cbafc9031148b1866f16c2be7aaa
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2026-07-14T03:27:59Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2026-07-14T03:28:04Z"}]}'
    field.cattle.io/projectId: local:p-j78jh
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOwc6DIBCE32XPP/5SLVXeZsEl0iAYdz00xndv0HtvM8nMN3PAQoITCoI9AHMughJL5mqLe5MXJmm2WBqPIomaWP7jBBZCIhLlShGWDVd1Mc4/SOgo/azPyDNY6J+67dou6NEZ7zD4se207genB2OCNv7h6IV4QTMuBBZuhrqnfdpZaGPFHxZaaoxX8mCPqgRlry/O8xsAAP//rwJNleMAAAA
    objectset.rio.cattle.io/id: fleet-bootstrap-data
spec: {}
apiVersion: v1
kind: Namespace
