metadata:
  name: cattle-fleet-system
  labels:
    field.cattle.io/projectId: p-j78jh
    kubernetes.io/metadata.name: cattle-fleet-system
    objectset.rio.cattle.io/hash: 4510303f19b6cbafc9031148b1866f16c2be7aaa
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2026-07-13T07:32:08Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2026-07-13T07:32:13Z"}]}'
    field.cattle.io/projectId: local:p-j78jh
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yNQY6EIBRE7/LXoyOjQyu3+eAn0kEwUr3oGO/eQfe9q0ql3jtoFfDMYDIHcUoZjJBTqTXbpzgUQbuH3DoGorQh/4aZDPkogsbmjIKdt+ZinD8U2Ur8el+4LGRo+Fdd3/VeTVY7y95NXa/UMFo1au2Vdn9WHswXNPEqZOhmNLe6vAtkrWvZxJE5agLjVeXn+QkAAP//upXJmdoAAAA
    objectset.rio.cattle.io/id: fleet-bootstrap-data
spec: {}
apiVersion: v1
kind: Namespace
