metadata:
  name: keycloak
  labels:
    kubernetes.io/metadata.name: keycloak
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2026-07-14T10:01:58Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2026-07-14T10:01:58Z"}]}'
    field.cattle.io/containerDefaultResourceLimit: '{}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
