metadata:
  name: passbolt
  labels:
    kubernetes.io/metadata.name: passbolt
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2026-07-15T08:19:16Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2026-07-15T08:19:16Z"}]}'
    field.cattle.io/containerDefaultResourceLimit: '{}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
spec: {}
apiVersion: v1
kind: Namespace
