metadata:
  name: p-j78jh
  labels:
    kubernetes.io/metadata.name: p-j78jh
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2026-07-13T07:31:47Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2026-07-13T07:31:47Z"}]}'
    lifecycle.cattle.io/create.namespace-auth: <REDACTED:env>
    management.cattle.io/no-default-sa-token: <REDACTED:env>
    management.cattle.io/system-namespace: 'true'
spec: {}
apiVersion: v1
kind: Namespace
