metadata:
  name: pvc-229b4955-4ccb-423e-ad41-bf6fc35ad5f7
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_52>
    volume.kubernetes.io/provisioner-deletion-secret-name: <REDACTED:env>
    volume.kubernetes.io/provisioner-deletion-secret-namespace: <REDACTED:env>
spec:
  capacity:
    storage: 30Gi
  csi:
    driver: <DOMAIN_52>
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-dc0092fa-030a-4bd2-bc22-b89d2c4f82d6
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-dc0092fa-030a-4bd2-bc22-b89d2c4f82d6
      journalPool: replicapool
      pool: replicapool
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_53>
    controllerPublishSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: otm
    name: otm-mysql-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
