metadata:
  name: pvc-7b436157-0638-43a7-88e8-ee0c8521fe20
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_52>
    volume.kubernetes.io/provisioner-deletion-secret-name: <REDACTED:env>
    volume.kubernetes.io/provisioner-deletion-secret-namespace: <REDACTED:env>
spec:
  capacity:
    storage: 1500Gi
  csi:
    driver: <DOMAIN_52>
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-48977b18-89ad-43e7-a9b3-ffef1cef808a
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-48977b18-89ad-43e7-a9b3-ffef1cef808a
      journalPool: replicapool
      pool: replicapool
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_53>
    controllerPublishSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-registry
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
