metadata:
  name: pvc-96848c70-3df6-45da-a231-1ec753916cdd
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_52>
    volume.kubernetes.io/provisioner-deletion-secret-name: <REDACTED:env>
    volume.kubernetes.io/provisioner-deletion-secret-namespace: <REDACTED:env>
spec:
  capacity:
    storage: 30Gi
  csi:
    driver: <DOMAIN_52>
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-33f93468-2a72-4b5d-885b-a70e1cf1cf55
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-33f93468-2a72-4b5d-885b-a70e1cf1cf55
      journalPool: replicapool
      pool: replicapool
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_53>
    controllerPublishSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: shift-handover
    name: shift-handover-storage-shift-handover-mongo-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
