metadata:
  name: pvc-f24611fa-4883-4c7e-b6d3-347f67235a94
  annotations:
    pv.kubernetes.io/provisioned-by: <DOMAIN_52>
    volume.kubernetes.io/provisioner-deletion-secret-name: <REDACTED:env>
    volume.kubernetes.io/provisioner-deletion-secret-namespace: <REDACTED:env>
spec:
  capacity:
    storage: 1Gi
  csi:
    driver: <DOMAIN_52>
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-3b6b3332-d5e6-4f82-94a5-eb5713783e58
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: '2'
      imageName: csi-vol-3b6b3332-d5e6-4f82-94a5-eb5713783e58
      journalPool: replicapool
      pool: replicapool
      storage.kubernetes.io/csiProvisionerIdentity: <DOMAIN_53>
    controllerPublishSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-jobservice
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
apiVersion: v1
kind: PersistentVolume
