metadata:
  name: default-token-fxk6l
  namespace: u-wwwzr4dilo
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 23c6a4ee-c7a1-4887-80af-bdce3ddeda6e
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
