metadata:
  name: vault-auth-token-zbqxm
  namespace: keycloak
  annotations:
    kubernetes.io/service-account.name: vault-auth
    kubernetes.io/service-account.uid: 73ff9c63-1ee0-46b9-8733-8de1db2150e0
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
