metadata:
  name: default-token-f66fv
  namespace: keycloak
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 40ac35d8-8a07-4044-a003-af1755492315
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
