metadata:
  name: keycloak-external
  namespace: keycloak
  annotations: {}
spec:
  ports:
  - name: https
    protocol: TCP
    port: 19097
    targetPort: 8443
  selector:
    app: keycloak
  clusterIP: <IP_76>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
