metadata:
  name: vault-auth
  namespace: keycloak
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: keycloak
  annotations:
    artifact.spinnaker.io/location: <REDACTED:env>
    artifact.spinnaker.io/name: <REDACTED:env>
    artifact.spinnaker.io/type: <REDACTED:env>
    moniker.spinnaker.io/application: <REDACTED:env>
    moniker.spinnaker.io/cluster: <REDACTED:env>
secrets:
- name: vault-auth-token-zbqxm
apiVersion: v1
kind: ServiceAccount
