metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: keycloak
  annotations:
    artifact.spinnaker.io/location: <REDACTED:env>
    artifact.spinnaker.io/name: <REDACTED:env>
    artifact.spinnaker.io/type: <REDACTED:env>
    moniker.spinnaker.io/application: <REDACTED:env>
    moniker.spinnaker.io/cluster: <REDACTED:env>
spec:
  ports:
  - name: httpp
    protocol: TCP
    port: 48080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 18443
    targetPort: 8443
  selector:
    app: keycloak
  clusterIP: <IP_75>
  type: ClusterIP
  externalIPs:
  - <CLEANUP_IP_5>
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
