metadata:
  name: clusterrolebinding-6tvz5
  generateName: clusterrolebinding-
  namespace: face-reco
  labels:
    authz.cluster.cattle.io/rtb-owner-updated: <REDACTED:env>
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-pdq5vm372s
roleRef:
  apiGroup: <DOMAIN_776>
  kind: ClusterRole
  name: read-only
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
