metadata:
  name: default-token-ld2ts
  namespace: face-reco
  annotations:
    field.cattle.io/projectId: local:p-67wv8
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 35d28f50-34c5-4185-be0b-477717c8c53c
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
