metadata:
  name: face-reco-be-secret
  namespace: face-reco
  labels:
    appname: face-reco
  annotations: {}
data:
  CATALINA_OPTS: <REDACTED:secret>
  TOMCAT_OPTS: <REDACTED:secret>
  admin_gen_id: <REDACTED:secret>
  admin_single_id: <REDACTED:secret>
  admin_username: <REDACTED:secret>
  app_mode: <REDACTED:secret>
  baseline_on_migrate: <REDACTED:secret>
  cip_api_server: <REDACTED:secret>
  cip_auth_server: <REDACTED:secret>
  cip_auth_server_sso: <REDACTED:secret>
  cip_auth_server_sub: <REDACTED:secret>
  cip_client_id: <REDACTED:secret>
  cip_client_secret: <REDACTED:secret>
  data_storage_path: <REDACTED:secret>
  db_mysql_host: <REDACTED:secret>
  db_mysql_name: <REDACTED:secret>
  db_mysql_password: <REDACTED:secret>
  db_mysql_port: <REDACTED:secret>
  db_mysql_username: <REDACTED:secret>
  useSwagger: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
