metadata:
  name: mysql-service
  namespace: face-reco
  labels:
    appname: face-reco
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: <IP_67>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
