metadata:
  name: spin-deck
  namespace: spinnaker
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: deck
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: local1.21.3
    cluster: spin-deck
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["<IP_72>"],"port":80,"protocol":"HTTP","serviceName":"spinnaker:spin-deck","ingressName":"spinnaker:spinnaker-ingress","hostname":"spinnaker.<COMPANY><DOMAIN_14>","path":"/","allNodes":false}]'
    moniker.spinnaker.io/application: <REDACTED:env>
    moniker.spinnaker.io/cluster: <REDACTED:env>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-deck
  template:
    metadata:
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: deck
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: local1.21.3
        cluster: spin-deck
    spec:
      volumes:
      - name: spin-deck-files-1346984691
        secret:
          secretName: <REDACTED:env>
          defaultMode: 420
      containers:
      - name: deck
        image: <COMPANY>-<DOMAIN_607>/spinnaker/deck:3.2.0-20200625152925
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: spin-deck-files-1346984691
          mountPath: /opt/spinnaker/config
        readinessProbe:
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        lifecycle: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
      - name: registrypullsecret
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
apiVersion: apps/v1
kind: Deployment
