metadata:
  name: spin-clouddriver-files-1555694734
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-clouddriver
data:
  2054179555-config: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
