metadata:
  name: spin-front50-files-1253799442
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-front50
data:
  credentials: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
