metadata:
  name: default-token-6f745
  namespace: spinnaker
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: b5f9fb75-fb66-44c8-bb77-950e8df85360
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
