metadata:
  name: spin-igor-files-292867571
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-igor
data:
  igor.yml: <REDACTED:secret>
  spinnaker.yml: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
