metadata:
  name: spin-fiat-files-783243827
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-fiat
data:
  fiat-local.yml: <REDACTED:secret>
  fiat.yml: <REDACTED:secret>
  spinnaker.yml: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
