metadata:
  name: spin-orca-files-987244119
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-orca
data:
  orca.yml: <REDACTED:secret>
  spinnaker.yml: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
