metadata:
  name: spin-clouddriver
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-clouddriver
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 7002
    targetPort: 7002
  selector:
    app: spin
    cluster: spin-clouddriver
  clusterIP: <IP_109>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
