metadata:
  name: spin-redis
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-redis
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: spin
    cluster: spin-redis
  clusterIP: <IP_117>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
