metadata:
  name: spin-orca
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-orca
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  selector:
    app: spin
    cluster: spin-orca
  clusterIP: <IP_116>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
