metadata:
  name: spin-echo
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-echo
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  selector:
    app: spin
    cluster: spin-echo
  clusterIP: <IP_111>
  type: ClusterIP
  sessionAffinity: <REDACTED:env>
apiVersion: v1
kind: Service
