metadata:
  name: kubelet-config
  namespace: kube-system
data:
  kubelet: "apiVersion: <DOMAIN_49>/v1beta1\nauthentication:\n  anonymous:\n    enabled:\
    \ false\n  webhook:\n    cacheTTL: 0s\n    enabled: true\n  x509:\n    clientCAFile:\
    \ /etc/kubernetes/pki/<DOMAIN_44>\nauthorization:\n  mode: Webhook\n  webhook:\n\
    \    cacheAuthorizedTTL: 0s\n    cacheUnauthorizedTTL: 0s\ncgroupDriver: systemd\n\
    clusterDNS:\n- <IP_3>\nclusterDomain: cluster.local\ncontainerRuntimeEndpoint:\
    \ \"\"\ncpuManagerReconcilePeriod: 0s\ncrashLoopBackOff: {}\nevictionPressureTransitionPeriod:\
    \ 0s\nfileCheckFrequency: 0s\nhealthzBindAddress: 127.0.0.1\nhealthzPort: 10248\n\
    httpCheckFrequency: 0s\nimageMaximumGCAge: 0s\nimageMinimumGCAge: 0s\nkind: KubeletConfiguration\n\
    logging:\n  flushFrequency: 0\n  options:\n    json:\n      infoBufferSize: \"\
    0\"\n    text:\n      infoBufferSize: \"0\"\n  verbosity: 0\nmemorySwap: {}\n\
    nodeStatusReportFrequency: 0s\nnodeStatusUpdateFrequency: 0s\nresolvConf: /run/systemd/resolve/<DOMAIN_40>\n\
    rotateCertificates: true\nruntimeRequestTimeout: 0s\nserverTLSBootstrap: true\n\
    shutdownGracePeriod: 0s\nshutdownGracePeriodCriticalPods: 0s\nstaticPodPath: /etc/kubernetes/manifests\n\
    streamingConnectionIdleTimeout: 0s\nsyncFrequency: 0s\nvolumeStatsAggPeriod: 0s\n"
apiVersion: v1
kind: ConfigMap
