metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: ".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n\
    \    kubernetes cluster.local <DOMAIN_38> <DOMAIN_39> {\n       pods insecure\n\
    \       fallthrough <DOMAIN_38> <DOMAIN_39>\n       ttl 30\n    }\n    prometheus\
    \ :9153\n    forward . /etc/<DOMAIN_40> {\n       max_concurrent 1000\n    }\n\
    \    cache 30 {\n       disable success cluster.local\n       disable denial cluster.local\n\
    \    }\n    loop\n    reload\n    loadbalance\n}\n"
apiVersion: v1
kind: ConfigMap
