metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    app: kube-proxy
data:
  config.conf: "apiVersion: <DOMAIN_41>/v1alpha1\nbindAddress: 0.0.0.0\nbindAddressHardFail:\
    \ false\nclientConnection:\n  acceptContentTypes: \"\"\n  burst: 0\n  contentType:\
    \ \"\"\n  kubeconfig: /var/lib/kube-proxy/<DOMAIN_42>\n  qps: 0\nclusterCIDR:\
    \ <IP_1>/16\nconfigSyncPeriod: 0s\nconntrack:\n  maxPerCore: null\n  min: null\n\
    \  tcpBeLiberal: false\n  tcpCloseWaitTimeout: null\n  tcpEstablishedTimeout:\
    \ null\n  udpStreamTimeout: 0s\n  udpTimeout: 0s\ndetectLocal:\n  bridgeInterface:\
    \ \"\"\n  interfaceNamePrefix: \"\"\ndetectLocalMode: \"\"\nenableProfiling: false\n\
    healthzBindAddress: \"\"\nhostnameOverride: \"\"\niptables:\n  localhostNodePorts:\
    \ null\n  masqueradeAll: false\n  masqueradeBit: null\n  minSyncPeriod: 0s\n \
    \ syncPeriod: 0s\nipvs:\n  excludeCIDRs: null\n  minSyncPeriod: 0s\n  scheduler:\
    \ \"\"\n  strictARP: false\n  syncPeriod: 0s\n  tcpFinTimeout: 0s\n  tcpTimeout:\
    \ 0s\n  udpTimeout: 0s\nkind: KubeProxyConfiguration\nlogging:\n  flushFrequency:\
    \ 0\n  options:\n    json:\n      infoBufferSize: \"0\"\n    text:\n      infoBufferSize:\
    \ \"0\"\n  verbosity: 0\nmetricsBindAddress: \"\"\nmode: ipvs\nnftables:\n  masqueradeAll:\
    \ false\n  masqueradeBit: null\n  minSyncPeriod: 0s\n  syncPeriod: 0s\nnodePortAddresses:\
    \ null\noomScoreAdj: null\nportRange: \"\"\nshowHiddenMetricsForVersion: \"\"\n\
    winkernel:\n  enableDSR: false\n  forwardHealthCheckVip: false\n  networkName:\
    \ \"\"\n  rootHnsEndpointName: \"\"\n  sourceVip: \"\""
  kubeconfig.conf: "apiVersion: v1\nkind: Config\nclusters:\n- cluster:\n    certificate-authority:\
    \ /var/run/secrets/<DOMAIN_43>/serviceaccount/<DOMAIN_44>\n    server: https://<CLEANUP_IP_7>:6443\n\
    \  name: default\ncontexts:\n- context:\n    cluster: default\n    namespace:\
    \ default\n    user: default\n  name: default\ncurrent-context: default\nusers:\n\
    - name: default\n  user:\n    tokenFile: /var/run/secrets/<DOMAIN_43>/serviceaccount/token"
apiVersion: v1
kind: ConfigMap
