metadata:
  name: extension-apiserver-authentication
  namespace: kube-system
data:
  client-ca-file: '-----BEGIN CERTIFICATE-----

    MIIDBTCCAe2gAwIBAgIIYpmvOK2GuPowDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE

    AxMKa3ViZXJuZXRlczAeFw0yNjA3MDkwNzI3MTdaFw0zNjA3MDYwNzMyMTdaMBUx

    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK

    AoIBAQCrfTAjmwRd0iztW23qBuhmzV2qmpNJ9p4lbX2ow1xrOP9nfJ8qiEoHO6Ws

    GhZ0qCy+wZdXeh5v2bcNxP4GRb3+Ky5uVSwgS1tG9W9LusAiZDmF1DAlNsaTLUVw

    oc2kewUt7n1I7nY3TazftVBjZ75com5X+KOdDDXooebOTnX4AWTg4f8YWUhsL9V0

    BjLsfZKM/WqAIE++p2pH0l+volBci1mLW7t47ewCnSK+paBLXUmq7WchMgavzuKl

    12EnyvpYinhzskByjETxuQ515K2+4+AA3dD9AGBN0eulY15TqmSy9fQ/F+UNDH1g

    iyKxYTFfNy8329nfgeKyimjvdXERAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP

    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRDs3OM52vQEe0EUYwinPkOGTXtjDAV

    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCBNU7ykMSz

    i4WZLmk5mjF0BG65LuEVFjNWEmVAxsIArZaHdGzYFjH+CXUJjIpimYMo+LcYO3aw

    2ON1Xv7hswT/dIRmlcJgmUdYirey1LukWtfADXUlsE+MLmGqND1msN981FK3GKZR

    5e8L71bgeX8YN/Lru9NYGmACuL05ASGsmBNVRYmupWvaNo6cEUMecikRl86ibEij

    ZOfsV28zGbow3allsuFjecgc6jNKczdJ+4XaKvSXAK49iNHOOKO7vJaLX2cKTOOL

    tmw9/2PAQaBC0ZvszLd9QOJbBExI2gKmK4aeXT67LIUDhaKD7T3+TDjPq6hiKD7B

    BKo0zA15CjPz

    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----

    MIIDBTCCAe2gAwIBAgIIKH9L8rjcSLYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE

    AxMKa3ViZXJuZXRlczAeFw0yNjA3MDkwOTA3MjVaFw0zNjA3MDYwOTEyMjVaMBUx

    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK

    AoIBAQDwcWM0N65SSwlGLkVg/UTW5bwwPDXZbHw2njfmddRoKOpU5Yp+LfilSQc5

    gZuZdx5+o2jMEXQxIBPg2O8dZBAUYNo2X+dgPb1pZbgTf1eXcwVMdSw+pfVKidsx

    3u8+E6+8tkqCqIsncaTv7/xmyQ6/fteCyzMWoopqxXNH3sjy+DGmwU9EVfSmuanA

    Op+N5EZbNPX+Zxm4fgzDIh4a1XlqBvh1smdyM3yv74zDjvhLSOUK+rwJlL09QNew

    ZfgXyB081gJHEozNJIEY0O6O0aGt9r9IZfUpBNAU6K3ZlC84w2i9azxz91XJ1qz9

    vsQPMqee5ybnA9F5XpcWVe+YB70LAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP

    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSSWc+jwmkdIQjheDh2aM8tu8x+9zAV

    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCUU9UZedBr

    8/woaw+Qkz2SdakT+cDTmDYQFtegF+vmSQc/kVpZH+ilPFtGrYurfzIVYgMaVZTT

    qbX74GtV8SWz6eziPhrBjAqREDEEhZ65VLY5CamFDY9jHqc5vJhu4MnAjuNfDBPu

    9rfQ6ghb4rKLHkjwBOem0Y84Sf+hIL00SFvbWcpdjNN0ShwcO9yGn5F+DLMTNaYL

    M/F4YEhkuWvhcHhVRqIzVj+rFNWTMhgMwmskq+s+XegYLdyGh0FtvogstJ72SR6C

    09zbIdDvatv0+2nBi3uO9mzs2qvLGTWn1aA2PDDqUlGZDwdS2/thBPZrpVjCw2Wz

    JdV2k3sPZtdC

    -----END CERTIFICATE-----

    '
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: '-----BEGIN CERTIFICATE-----

    MIIDETCCAfmgAwIBAgIIa/pSV0iZf/EwDQYJKoZIhvcNAQELBQAwGTEXMBUGA1UE

    AxMOZnJvbnQtcHJveHktY2EwHhcNMjYwNzA5MDcyNzE3WhcNMzYwNzA2MDczMjE3

    WjAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTCCASIwDQYJKoZIhvcNAQEBBQAD

    ggEPADCCAQoCggEBAOWrN9dEg40HyPYM85043OeySGbqeJnJ9Uxxh56x6z7EmayU

    DgoZ7Hc/q8jhQ5OiSsoHTOOCuVTjcsJ+pPePoH92x66agS+gHkE7g0k2oGXDlCkX

    74ANB1qd2RYUvyq/+DD54W+NLjiLpb7AdGyKBFHNSxX6NR5Nci2/GClZmSCNXXxJ

    iJoINXQv+euN+QrEpBpKLfATYSGsVm01Sp6O1EuhbGeYiZEFaLoKryhHsWurFqPM

    dYpavILuNlqki641O/1M8HfQ0yMBuQJ43xETEpiBZjgG5tnG5CD/jnyOTstOssr/

    +FbEt8ovt6pZpS80mGZ+ljDrx6gPCnjKcX7FYbMCAwEAAaNdMFswDgYDVR0PAQH/

    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFAZXc7+eIocXi6rGRHAA

    gao+ALewMBkGA1UdEQQSMBCCDmZyb250LXByb3h5LWNhMA0GCSqGSIb3DQEBCwUA

    A4IBAQBPn678y5FW/4/MYvhyLs+QUZo6Xqao22bILZipu0e3zZFbD+XSftlBZSTN

    020W209DZCZhLx0655EUUmFQQIa4fgZ/19pq0S2zLvQ1R699sMUxJHDMi09nnjNn

    sI5Dbnvh1fILlIA3pbVH7I0RjQ986UmwdTmiLNSmho+Oci4y3JQ0uZqDOFSdBOFy

    QY3L6DDbun70ywZcMZGWiV7lSBwbfcTuC6no5JAwRqaWqa5j/pdIRcnYd7Hc+BVk

    ySUoG3QVaBJwyh9Cx+nC6+hU9MdNLCyc3yQaZ6NfITlUPCjVKRIfSJ9uNRGBuxyk

    GIGw39kQ36O2c8KVvFy4iXrApEXi

    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----

    MIIDETCCAfmgAwIBAgIIUmpJ8pN7bbkwDQYJKoZIhvcNAQELBQAwGTEXMBUGA1UE

    AxMOZnJvbnQtcHJveHktY2EwHhcNMjYwNzA5MDkwNzI1WhcNMzYwNzA2MDkxMjI1

    WjAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTCCASIwDQYJKoZIhvcNAQEBBQAD

    ggEPADCCAQoCggEBAMAZK7BuwnqGTmvKdRmb9dI4guXVjWC0erSdvQMqG/33Vbgc

    ZVDuzoHgidticF/D1ORIXBF/b2ARFl9L53a8jyJBDKq30wMC+6HGlKsUA6iU2tZx

    H3DnVyJwSDSAI5pr7ukdDIRX+VpIJqOIpmgMsR4rovb8cI21cx5U3L8g1xR7yWDo

    Henu4dZC/xkjMHDdq8/rKrjWC4MXB845EV1GW7BoRSRfTc6S0xlFsSQr20UtqzYG

    lN3LLj5jSrzthanWSCk7CPTMy5Kyp7NJMjkJhxTVIe/zr3qOBN0xL0CZtDBbabcl

    2B3SsNBKxSGUREXEr0MhwOtnmXlFSvwtuAjyVz0CAwEAAaNdMFswDgYDVR0PAQH/

    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGJFb13RD5JoTQjAwfDr

    7ycwkjXMMBkGA1UdEQQSMBCCDmZyb250LXByb3h5LWNhMA0GCSqGSIb3DQEBCwUA

    A4IBAQAY9A10QaBgdnQ+c6HV2APKPGHKv0xNVmrCCdI3wsWgW/DTNmNpEd9J9stF

    xZfRARGNUluarh0UGDfOcAsHn4ahNy093CL+BCYmAWrPCaQ/xpHcFPJe6PStKGYR

    d3C9+yeIQBFyLjpJ1YtBqIQ78BoySzRqJ/I6mUsC4f0eclbJcq26ZYHxES/DzbpQ

    MF9Y4pkMq4obS6Et1bMmDKklTCkfSpuf/liq+EZBqEDkuwoOlhdaMENmPJUc8H/3

    /h/p8rw6sFddfDVddfFsSpPlF0JXXjpf5zs6MSzXbGA8aZAjHqyBFpAxe9BRFX6F

    OJV61abP60qKdtnF1LsEB+z4ptuq

    -----END CERTIFICATE-----

    '
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
apiVersion: v1
kind: ConfigMap
