metadata:
  name: default-token-nvqnl
  namespace: u-m6qmoqpsah
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 1c58be82-7a45-4865-b5ea-566fcc531134
data:
  ca.crt: <REDACTED:secret>
  namespace: <REDACTED:secret>
  token: <REDACTED:secret>
type: <DOMAIN_138>/service-account-token
apiVersion: v1
kind: Secret
