metadata:
  name: dsd-secret
  namespace: security-cloud
data:
  JWT_SECRET: <REDACTED:secret>
  MONGODB_URL: <REDACTED:secret>
  NODE_ENV: <REDACTED:secret>
  SEND_EMAIL_PASSWORD: <REDACTED:secret>
  SEND_EMAIL_USERNAME: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
