metadata:
  name: rolebinding-2p47r
  generateName: rolebinding-
  namespace: local
  labels:
    cattle.io/creator: norman
    ec3b180c-fb3b-4681-90db-da90ac9afa67: memberhsip-binding-owner
    p-wnc8s_u-pg7qxfe7lh-member: membership-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-pg7qxfe7lh
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: p-wnc8s-projectmember
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
