metadata:
  name: p-67wv8-projectmember
  namespace: local
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - get
  apiGroups:
  - <DOMAIN_528>
  resources:
  - projects
  resourceNames:
  - p-67wv8
apiVersion: <DOMAIN_776>/v1
kind: Role
