metadata:
  name: p-67wv8-u-muss3v2lek-member-project-member
  namespace: local
  labels:
    cattle.io/creator: norman
    p-67wv8_u-muss3v2lek-member: prtb-in-cluster-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-muss3v2lek
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: project-member
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
