metadata:
  name: project-owner
  namespace: local
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - catalogtemplates
- verbs:
  - '*'
  apiGroups:
  - '*'
  resources:
  - catalogtemplateversions
- verbs:
  - list
  - watch
  - get
  apiGroups:
  - '*'
  resources:
  - notifiers
- verbs:
  - watch
  - get
  - list
  apiGroups:
  - '*'
  resources:
  - clustercatalogs
apiVersion: <DOMAIN_776>/v1
kind: Role
