metadata:
  name: p-67wv8-prtb-7m9nc-read-only
  namespace: local
  labels:
    cattle.io/creator: norman
    p-67wv8_prtb-7m9nc: prtb-in-cluster-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-pdq5vm372s
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: read-only
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
