metadata:
  name: project-member
  namespace: local
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - notifiers
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - clustercatalogs
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - catalogtemplates
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - catalogtemplateversions
apiVersion: <DOMAIN_776>/v1
kind: Role
