metadata:
  name: cluster-member
  namespace: local
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clusterroletemplatebindings
- verbs:
  - create
  apiGroups:
  - <DOMAIN_528>
  resources:
  - projects
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - nodes
  - nodepools
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - nodes
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - persistentvolumes
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - storageclasses
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - apiservices
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clusterevents
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clusterloggings
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clusteralertrules
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clusteralertgroups
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - notifiers
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clustercatalogs
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clustermonitorgraphs
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - catalogtemplates
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_528>
  resources:
  - catalogtemplateversions
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - <DOMAIN_781>
  resources:
  - clusterrepos
- verbs:
  - get
  apiGroups:
  - <DOMAIN_528>
  resources:
  - clusters
  resourceNames:
  - local
apiVersion: <DOMAIN_776>/v1
kind: Role
