metadata:
  name: rolebinding-zndff
  generateName: rolebinding-
  namespace: local
  labels:
    497a36f3-564c-49fb-95e4-cb570722d303: memberhsip-binding-owner
    cattle.io/creator: norman
    p-t2pmj_creator-project-owner: membership-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: user-9h9cp
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: p-t2pmj-projectowner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
