metadata:
  name: rolebinding-cz9qp
  generateName: rolebinding-
  namespace: local
  labels:
    cattle.io/creator: norman
    p-67wv8_creator-project-owner: membership-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-p7vaiakhge
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: p-67wv8-projectowner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
