metadata:
  name: crtb-t69r9-cluster-owner
  namespace: local
  labels:
    cattle.io/creator: norman
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-w6k48
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: cluster-owner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
