metadata:
  name: rolebinding-phmm6
  generateName: rolebinding-
  namespace: local
  labels:
    cattle.io/creator: norman
    p-67wv8_prtb-7m9nc: membership-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: u-pdq5vm372s
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: p-67wv8-projectmember
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
