metadata:
  name: p-wnc8s-creator-project-owner-project-owner
  namespace: local
  labels:
    80e4934c-23e6-4432-87b5-44aa1597089f: prtb-in-cluster-binding-owner
    auth.management.cattle.io/rtb-label-updated: <REDACTED:env>
    cattle.io/creator: norman
    p-wnc8s_creator-project-owner: prtb-in-cluster-binding-owner
subjects:
- kind: User
  apiGroup: <DOMAIN_776>
  name: user-9h9cp
roleRef:
  apiGroup: <DOMAIN_776>
  kind: Role
  name: project-owner
apiVersion: <DOMAIN_776>/v1
kind: RoleBinding
