metadata:
  name: read-only
  namespace: local
  labels:
    cattle.io/creator: norman
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - notifiers
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - '*'
  resources:
  - clustercatalogs
apiVersion: <DOMAIN_776>/v1
kind: Role
