metadata:
  name: user-7qttr
  namespace: cattle-local-user-passwords
  annotations:
    cattle.io/password-hash: <REDACTED:env>
    field.cattle.io/projectId: local:p-j78jh
data:
  password: <REDACTED:secret>
  salt: <REDACTED:secret>
type: Opaque
apiVersion: v1
kind: Secret
