metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.8.0
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
secrets:
- name: vault-token-lt6pv
apiVersion: v1
kind: ServiceAccount
