metadata:
  name: vault-agent-injector
  namespace: vault
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-agent-injector
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
secrets:
- name: vault-agent-injector-token-jzf8w
apiVersion: v1
kind: ServiceAccount
